### PR TITLE
Fix broken source

### LINKED ISSUE #13916: Reaper Scans (English): JSON parse failing, again
### Source information and language

Reaper scans 1.3.38

### Steps to reproduce

1. Open a manga
2. Try to update it

### Expected behavior

It should update the manga, and add new chapters

### Actual behavior

Giving JSON error as Toast

### Tachiyomi version

0.13.6

### Android version

Android 9

### Other details

Screenshot_2022-10-18-17-22-33-328_eu kanade tachiyomi
Adding ss

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by h-hyuuga**
Resolves #13916

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 1]
```diff
@@ -176,66 +179,68 @@ class ReaperScans : ParsedHttpSource() {
...
-        var document = response.asJsoup()
+        val document = response.asJsoup()
         val chapters = mutableListOf<SChapter>()
+        document.select(chapterListSelector()).forEach { chapters.add(chapterFromElement(it)) }
+        var hasNextPage = document.selectFirst(chapterListNextPageSelector()) != null
+
+        if (!hasNextPage)
+            return chapters
 
         val csrfToken = document.selectFirst("meta[name=csrf-token]")?.attr("content")
```
Comment (AntsyLich) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt:193]: Make this 1 line

Comment (CarlosEsco) [reply src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt:193]: Can make it one line when it breaks again
