### PR TITLE
MadTheme: update rate limit for chapter endpoint

### LINKED ISSUE #13182: MangaXYZ: Add rate limiting to requests
### Source information and language

MangaXYZ 1.3.8

### Steps to reproduce

i update my library and it says 129 update error 
and shows error 429

### Expected behavior

i expected a good outcome

### Actual behavior

it says Error 429

### Tachiyomi version

1.8.5

### Android version

Android 8

### Other details

[Screenshot_20220825-135815_Chrome](https://user-images.githubusercontent.com/112059542/186586393-3ade9faa-f254-4e66-9932-b8b5570b1540.jpg)`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #13182

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt [hunk 1]
```diff
@@ -150,6 +161,37 @@ abstract class MadTheme(
...
+        if (response.code in 200..299) {
+            return super.chapterListParse(response)
+        }
+
+        // Try to use message from site
+        response.body?.let { body ->
+            val message: String? = json
+                .decodeFromString<JsonObject>(body.string())["message"]
+                ?.jsonPrimitive
+                ?.toString()
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt:187]: Using `toString()` will return the JSON representation and not the actual value IIRC.

```suggestion
                ?.content
```

Comment (vetleledaal) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt]: `.toString()` returns it with surrounding quotes, `.content` is correct
