### PR TITLE
Fix date format for Harimanga and DuniaKomik.id

### LINKED ISSUE #17153: Harimanga wrong chapter release date
### Source information

Harimanga 1.4.33

### Source language

English

### Steps to reproduce

1. Open Harimanga
2. Open any manga

### Expected behavior

The release date should be the same as on the website.

### Actual behavior

Screenshot_2023-07-17-11-17-24-976_eu kanade tachiyomi
Screenshot_2023-07-17-11-17-37-763_eu kanade tachiyomi

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Having the same problem too in DuniaKomik.id 1.4.26

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by MuhamedZ1**
Also fixed the DuniaKomik.id date problem as stated in the issue. (closes #17153)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by vetleledaal** [comment]
> - [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")

You must use the mentioned keyword ([or similar](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) so GitHub links the issue properly.

**Comment by vetleledaal** [comment]
/edit-tile "Fix date format for Harimanga and DuniaKomik.id"

**Comment by vetleledaal** [comment]
/edit-title "Fix date format for Harimanga and DuniaKomik.id"

File: multisrc/overrides/mangathemesia/duniakomikid/src/DuniaKomikId.kt [hunk 1]
```diff
@@ -2,7 +2,7 @@ package eu.kanade.tachiyomi.extension.id.duniakomikid
 
 import eu.kanade.tachiyomi.multisrc.mangathemesia.MangaThemesia
 
-class DuniaKomikId : MangaThemesia("DuniaKomik.id", "https://duniakomik.id", "id") {
+class DuniaKomikId : MangaThemesia("DuniaKomik.id", "https://duniakomik.id", "id", dateFormat = SimpleDateFormat("MMMM dd, yyyy", Locale("id", "ID"))) {
```
Comment (vetleledaal) [inline multisrc/overrides/mangathemesia/duniakomikid/src/DuniaKomikId.kt:5]: missing import for SimpleDateFormat and Locale

**Review by vetleledaal — APPROVED** [review]
