### PR TITLE
Temporary fix HTTP 103 in OPEX

### LINKED ISSUE #13775: One Piece Ex: HTTP error 103
### Source information and language

One Piece Ex 1.3.5 (Brasil)

### Steps to reproduce

Click in the extension

### Expected behavior

would work normally

### Actual behavior

this HTTP error 103 appears

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 11

### Other details

the site works normally, maybe it could be the design that is giving this error, I've never had this error before so I don't know

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by alessandrojean**
Closes #13775.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/pt/opex/src/eu/kanade/tachiyomi/extension/pt/opex/OnePieceEx.kt [hunk 1]
```diff
@@ -221,6 +231,33 @@ class OnePieceEx : ParsedHttpSource() {
...
     override fun latestUpdatesNextPageSelector() = throw UnsupportedOperationException("Not used")
 
+    private fun bypassHttp103Intercept(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+
+        if (request.url.pathSegments[0] != "mangas") {
+            return chain.proceed(request)
+        }
+
+        val bypasserUrl = "https://translate.google.com/translate".toHttpUrl().newBuilder()
```
Comment (arkon) [inline src/pt/opex/src/eu/kanade/tachiyomi/extension/pt/opex/OnePieceEx.kt:241]: Is it worth checking if it's explicitly a 103 response, or is that always the case?

Comment (alessandrojean) [reply src/pt/opex/src/eu/kanade/tachiyomi/extension/pt/opex/OnePieceEx.kt:241]: Hmm, I haven't checked if it's the case tbh, but I think it is. Will confirm in a moment.

Comment (alessandrojean) [reply src/pt/opex/src/eu/kanade/tachiyomi/extension/pt/opex/OnePieceEx.kt:241]: Checked now, seems to always be returning it. Probably not worth doing an extra call just to check if it returns 103.
