### PR TITLE
Fix VCPVMP

### LINKED ISSUE #13623: VCP/VMP: No results found
### Source information and language

Spanish extension: VCP/VMP 1.3.6(last version)

### Steps to reproduce

Install VCP/VMP extension and open it in tachiyomi.

### Expected behavior

Can search content in extension, can sort content in extension, can download content in extension, can view content in extension, in general can use extension.

### Actual behavior

Home page extension only load the first time, if you do something and return to home page extension, you will get this:
Screenshot_2022-09-28-19-57-15-931_eu kanade tachiyomi
I can't search content in extension:
Screenshot_2022-09-28-19-59-35-580_eu kanade tachiyomi

 I can't sort content in extension:
Screenshot_2022-09-28-19-59-46-213_eu kanade tachiyomi

 in general I can't use extension because doesn't work properly.

### Tachiyomi version

Tachiyomi 0.13.6

### Android version

Android 10

### Other details

Screenshot_2022-09-28-19-51-39-342_eu kanade tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

@arkon 
@edgarMejia 
@Neoterux 
@jopejoe1

### PR DESCRIPTION
**Pull request by seew3l**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #13623

### CODE REVIEW

File: src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMP.kt [hunk 1]
```diff
@@ -27,25 +27,35 @@ open class VCPVMP(override val name: String, override val baseUrl: String) : Par
...
-    override fun popularMangaNextPageSelector() = "ul.pagination > li.active + li"
+    override fun popularMangaNextPageSelector() = "div.wp-pagenavi > span.current + a"
 
     override fun mangaDetailsParse(document: Document) = SManga.create().apply {
-        document.select("div#catag").let {
-            genre = document.select("div#tagsin > a[rel=tag]").joinToString { it.text() }
-            status = SManga.UNKNOWN
-            thumbnail_url = document.select(pageListSelector).firstOrNull()?.attr("abs:src")
+        document.select("div.tax_post").let {
+            status = SManga.COMPLETED
```
Comment (alessandrojean) [inline src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMP.kt:46]: Are these titles single-chapter always and never receive new updates? If so, consider adding `update_strategy` as well. In that way, these titles will be always skipped during global update as they will never receive any new chapters.

```suggestion
            status = SManga.COMPLETED
            update_strategy = UpdateStrategy.ONLY_FETCH_ONCE
```

You need to add the import as well

```kotlin
import eu.kanade.tachiyomi.source.model.UpdateStrategy
```
