### PR TITLE
TuMangaOnline: Fix chapter images don't load and no pages found for some chapters

### LINKED ISSUE #16263: TuMangaOnline: Images are not loading due to site bad certificate
### Source information

TuMangaOnline 1.4.41

### Source language

Spanish 

### Steps to reproduce

1.Install TuMangaOnline extension if not already installed
2. Select any series from TuMangaOnline 
3. When opening any chapter, it shows "The image couldn't be loaded"
4. When "Retry" button is clicked it doesn't load the image.

### Expected behavior

When opening any chapter from the extension, it should show the images for the chapter.

### Actual behavior

Images are not loading
Screenshot_2023-05-01-18-43-03-89_afd66b7916d19a60815f56273408b73e

### Tachiyomi version

Stable 0.14.6

### Android version

Android 12

### Other details

In the TuMangaOnline website the Images actually load without issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by seew3l**
Closes #16263

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt [hunk 1]
```diff
@@ -255,8 +261,43 @@ class TuMangaOnline : ConfigurableSource, ParsedHttpSource() {
         }
     }
 
-    // Note: At this moment (24/08/2021) it's necessary to make the image request with headers to prevent 403.
-    override fun imageRequest(page: Page) = GET(page.imageUrl!!, headers)
+    private var loadWebView = true
+    // Note: At this moment (05/04/2023) it's necessary to make the image request with headers to prevent 403.
+    override fun imageRequest(page: Page): Request {
```
Comment (alessandrojean) [inline src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt:266]: It's better to do this in an interceptor actually. The `request` methods aren't supposed to do any processing and additional network calls.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt (hunk 1 above)
Comment (seew3l) [reply src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt]: When I test it, when making the call it will return an exception, not an error code.
Also, the DoH only fixes the ISP blocking.

**Review by alessandrojean — APPROVED** [review]

**Review by alessandrojean — APPROVED** [review]
