### PR TITLE
cubari: prevent `NullPointerException` when key is 084 and chapter_number is 84

### LINKED ISSUE #13772: Cubari refuses to open or download any manga chapters.
### Source information and language

Cubari 1.3.14 (All)

### Steps to reproduce

1. Open up a manga using Cubari
2. Try downloading or reading it

### Expected behavior

It should have opened the chapter up or downloaded it.

### Actual behavior

However there was two different things that happened with it.

1. When trying to download this happened. 
Screenshot_20221008-125949

2. When opening a chapter it brings up the black screen and  current page scroll setting message as usual to load the image. But it then kicks you out back to the chapter select and produces a blank message.

### Tachiyomi version

Stable 0.13.6

### Android version

Android version: 10

### Other details

It could have just been the one manga or that Cubari only works via opening it in the website.
EDIT #1:
Only Chapters that I recently found out that do work for the manga I'm trying to read (https://cubari.moe/read/gist/Z2lzdC9mdW5reWhpcHBvLzcxMjRhZjUyMWExMDU5NDVhNGRmNmEzMzFjOWZjZTU5L3Jhdy9vcG0td2MuanNvbg) are from 100 to the latest chapter. Everything thing else seems to not work.
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mobi2002**
fixes #13772 again

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt [hunk 1]
```diff
@@ -364,6 +366,15 @@ open class Cubari(override val lang: String) : HttpSource() {
                 ?: jsonObj["cover"]?.jsonPrimitive?.content ?: ""
         }
 
+    private fun removeLeadingZeros(jsonObject: JsonObject): JsonObject {
```
Comment (alessandrojean) [inline src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt:369]: You can likely simplify (or even remove this function entirely) by using `mapKeys`.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-keys.html
