### PR TITLE
Fix LeerCapitulo

### LINKED ISSUE #16240: LeerCapitulo: Pages do not load
### Source information

Leercapitulo versión  1.4.4

### Source language

Español

### Steps to reproduce

Debería de cargar las paginas

### Expected behavior

Carga normal en las paginas de los capítulos 

### Actual behavior

No cargo las paginas y ni deja recargarlo

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

Solo sucede en la extensión de Leercapitulo 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by seew3l**
Now the extension retrieves the necessary strings to decode the pages images from this repository:

https://github.com/seew3l/tachiyomi-scripts

Closes #16240

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt [hunk 1]
```diff
@@ -146,23 +147,32 @@ class LeerCapitulo : ParsedHttpSource(), ConfigurableSource {
...
             ?.split("-")
 
+        val useReversedString = orderList?.any { it == "01" }
+
         val arrayData = document.selectFirst("#arraydata")!!.text()
 
+        val keyDocument = client.newCall(GET(keyRepoUrl)).execute().asJsoup()
+        val keyList = keyDocument.body().text().split(" ")
+        val key1 = keyList[0]
+        val key2 = keyList[1]
```
Comment (AntsyLich) [inline src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt:164]:
```suggestion
        val (key1, key2) = client.newCall(GET(keyRepoUrl)).execute().body.string().split(" ")
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

File: src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt [hunk 2]
```diff
@@ -13,6 +13,7 @@ import eu.kanade.tachiyomi.source.model.Page
 import eu.kanade.tachiyomi.source.model.SChapter
 import eu.kanade.tachiyomi.source.model.SManga
 import eu.kanade.tachiyomi.source.online.ParsedHttpSource
+import eu.kanade.tachiyomi.util.asJsoup
```
Comment (AntsyLich) [inline src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt:16]:
```suggestion
```

**Comment by jazi15** [comment]
Hola buenas tardes, no entiendo nada de esto, alguien me explica? Porque obviamente me esta pasando que no puedo entrar a ningún capítulo de leercapitulo. Gracias.
