### PR TITLE
xCaliBR Scans: Update anti scrap logic

### LINKED ISSUE #10528: Xcalibr scans mirrored/split images
### Source information

XCalibr Scans 1.2.16

### Steps to reproduce

1) Open the XCalibr Scans on the list of extension on the app.
2) Select a random Manhwa and try to read 1 chapter
3) Manhwa opens with a mirrored image or split image, the image looks fine on webview.

### Expected behavior

The image should display properly.

### Actual behavior

The image appeared mirrored or split.

### Tachiyomi version

TachiJ2K 1.4.4

### Android version

Android 9

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AntsyLich**
Fixes #10528

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/mangathemesia/xcalibrscans/src/Http103Interceptor.kt [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+import okhttp3.Request
+import okhttp3.Response
+import okhttp3.ResponseBody.Companion.toResponseBody
+import uy.kohesive.injekt.Injekt
+import uy.kohesive.injekt.api.get
+import java.io.IOException
+import java.util.concurrent.CountDownLatch
+import java.util.concurrent.TimeUnit
+
+// TODO: Remove when OkHttp can handle http 103 responses
```
Comment (arkon) [inline multisrc/overrides/mangathemesia/xcalibrscans/src/Http103Interceptor.kt:25]: I'd rather this happen in the app so all sources benefit from it. I can cherry pick it back to a stable release.

Comment (AntsyLich) [reply multisrc/overrides/mangathemesia/xcalibrscans/src/Http103Interceptor.kt:25]: Hmm sure that works too
