### PR TITLE
Manga18fx: fix parsing

### LINKED ISSUE #7386: [Bug] <Manga18 Fx>: <HTTP eror 404: Check Website in WebView still doesn't work after opening in WebView>
## Device information
- Tachiyomi version:  Stable 0.11.1
- Android version: 11

## Source information
- Name: Manga18 Fx
- Extension version: 1.2.5

## Steps to reproduce
1.  Open in WebView
2.  Still asking me to check in WebView
### Expected behavior
Describe what should have happened

Manga/Manhwa should show up the list on the site.

### Actual behavior
Describe what happens instead
The extension has an error that cannot access and asked  to check in webview to see if it is running fine, it runs fine but when I get back to tachiyomi it still has the error.

### PR DESCRIPTION
**Pull request by stevenyomi**
Fixes #7386

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -222,7 +222,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Manga-Online.co", "https://www.manga-online.co", "th", className = "MangaOnlineCo"),
         SingleLang("Manga-Scantrad", "https://manga-scantrad.net", "fr", className = "MangaScantrad", overrideVersionCode = 2),
         SingleLang("Manga-TX", "https://manga-tx.com", "en", className = "Mangatxunoriginal"),
-        SingleLang("Manga18 Fx", "https://manga18fx.com", "en", overrideVersionCode = 1),
+        SingleLang("Manga18fx", "https://manga18fx.com", "en", isNsfw = true, overrideVersionCode = 2),
```
Comment (arkon) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:225]: Is the rename necessary? Kind of messes up downloads.

Comment (stevenyomi) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:225]: This extension has been broken for more than a year, so I think the rename is acceptable. No one should be using it recently.
