### PR TITLE
[RU]NudeMoon change domain and other fixes

### LINKED ISSUE #7428: [Bug] <Nude-Moon>: <Covers don't load automatically>
---

## Device information
- Tachiyomi version: 0.11.1
- Android version: 11

## Source information
- Name: Nude-Moon
- Extension version: 1.2.7

## Steps to reproduce
1. Open source 
2. After opening the source, you can see that the covers are not loaded 

### Expected behavior
Covers are loaded when the source is opened

### Actual behavior
Covers are not loaded automatically. But when you open some manga, the cover is loaded to it, that is, to see other covers, you need to open each manga in turn

### LINKED ISSUE #11526: Nude-Moon: Error during HTML parsing
### Source information

Nude-Moon 1.2.8

### Steps to reproduce

I have been trying to open a source for a very long time, it always gives the same error, I am authorized through webview. Shows a similar error when trying to open any title.
Screenshot_20220419_223855
Screenshot_20220419_223812

### Expected behavior

Title opening

### Actual behavior

Error

### Tachiyomi version

0.13.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #13191: Nude-Moon: HTML parsing is failing
### Source information and language

Nude-Moon 1.3.8 (Russian)

### Steps to reproduce

1. Open Nude-Moon extension
2. I see manga list with same cover
3. Occurs error

### Expected behavior

Open and read manga

### Actual behavior

When opening a manga in the application, an error occurs! Attempt to invoke virtual method 'org.jsoup.nodes.Element org.jsoup.nodes.Element.parent()' on a null object reference. Same error when updating manga. Through the webview, everything opens.

### Tachiyomi version

Preview r4821

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #13831: NudeMoon: Changed their domain
### Source information and language

Nude-Moon 1.3.8 Ru

### Source new URL

https://nude-moon.me/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by abubaca4**
Closes #13831
Closes #13191
Closes #11526
Closes #7428

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by abubaca4** [comment]
Rewrited to parse mobile site version
Fix Covers load, chapter list, add scanlator and some other parse fix

File: src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt [hunk 1]
```diff
@@ -123,26 +124,36 @@ class Nudemoon : ParsedHttpSource() {
...
+        manga.genre = document.select("table.news_pic2 div.tag-links a").joinToString { it.text() }
         manga.description = document.select(".description").text()
-        manga.thumbnail_url = document.select("tr[valign=top] img[class^=news]").attr("abs:src")
+        manga.thumbnail_url = document.selectFirst("div.gallery-item img.textbox").attr("abs:data-src")
 
         return manga
     }
 
     override fun chapterListRequest(manga: SManga): Request {
+        val mangaDocument: Document
```
Comment (alessandrojean) [inline src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt:144]: If you can make the method only return the request itself as the name implies, it will be better.

Additional calls can be done at the `chapterListParse` method if needed.
