### PR TITLE
fix(uk/honeymanga): Fix chapter list

### LINKED ISSUE #19452: Honeymanga json error
### Source information

Honeymanga 1.4.1

### Source language

Ukrainian

### Steps to reproduce

1. Install extention
2. Update manga page

### Expected behavior

List of chapters updates

### Actual behavior

error
Screenshot_2023-12-28-15-13-22-778_eu kanade tachiyomi

### Tachiyomi version

1.14.7

### Android version

Android 13

### Other details

When trying to update chapters list getting error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #19452 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt [hunk 1]
```diff
@@ -37,112 +35,102 @@ class HoneyManga : HttpSource() {
...
     override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
         if (query.length >= 3) {
-            return GET(
-                "$SEARCH_API_URL/api/v1/title/search-matching".toHttpUrl()
-                    .newBuilder()
-                    .addQueryParameter("query", query)
-                    .toString(),
-                headers,
-            )
+            val url = "$SEARCH_API_URL/v2/manga/pattern?query=$query"
```
Comment (alessandrojean) [inline src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt:59]: Avoid passing strings directly as query parameter as it may cause encoding issues. The previous implementation using the URL builder was more safer.

```suggestion
            val url = "$SEARCH_API_URL/v2/manga/pattern".toHttpUrl().newBuilder()
                .addQueryParameter("query", query)
                .build()
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]
