### PR TITLE
MangaRawRU: fix page order

### LINKED ISSUE #14734: MangaRawRU manga pages out of order
### Source information and language

MangaRawRU v1.3.4 (ja.mangarawru)

### Steps to reproduce

Download or view this chapter on tachiyomi app.
https://mangaraw.ru/chapters/%e3%81%91%e3%82%82%e3%81%ae%e3%81%bf%e3%81%a1%ef%bc%88%e6%9a%81%e3%81%aa%e3%81%a4%e3%82%81%ef%bc%89%e3%80%90%e7%ac%ac60%e8%a9%b1%e3%80%91-%e6%bc%ab%e7%94%bb-raw-free/

### Expected behavior

Pages should be in order.

### Actual behavior

Pages are out of order.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mao09**
Close #14734

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/mangaraw/mangarawru/src/MangaRawRU.kt [hunk 1]
```diff
@@ -59,4 +60,16 @@ class MangaRawRU : MangaRawTheme("MangaRawRU", "https://mangaraw.ru") {
     override fun pageSelector(): Evaluator {
         return Evaluator.Tag("img")
     }
+
+    override fun pageListParse(document: Document): List<Page> {
+
+        val position = 32
+        val parser = ImageListParser(document.html(), position)
+
+        val imageList = parser.getImageList() ?: throw Exception("Not found page.")
```
Comment (alessandrojean) [inline multisrc/overrides/mangaraw/mangarawru/src/MangaRawRU.kt:69]: Can just return a `emptyList()` so the app show the error in the language the user is using the app. Alternatively you can rewrite like this probably:

```kotlin
return parser.getImageList()
    .mapIndexed { i, imageUrl -> Page(i, imageUrl = imageUrl) }
```

If the list is empty, then the `mapIndexed` will not be executed and an empty list will be returned, so the elvis operator (`?:`) can be avoided.

**Review by alessandrojean — CHANGES_REQUESTED** [review]
