### PR TITLE
MangaMx: Moved to MangaOni

### LINKED ISSUE #14227: MangaMx: Changed their domain
### Source information and language

MangaMx 1.1.13 (español)

### Steps to reproduce

Abre la extensión , busca en la barra de búsqueda o filtra un manga, y lo encuentas

### Expected behavior

Abrí la barra de búsqueda o filtrar un manga, te saldrían los resultados 

### Actual behavior

No funciona la barra de búsqueda ni los filtros 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

La barra de búsqueda sale expected of the objetc 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by seew3l**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #14227

### CODE REVIEW

File: src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaOni.kt [hunk 1]
```diff
@@ -152,8 +154,9 @@ open class MangaMx : ConfigurableSource, ParsedHttpSource() {
 
             return MangasPage(mangas, hasNextPage)
         } else {
-            val result = json.decodeFromString<ResponseDto>(response.body!!.string())
-            if (result.mangaList.isEmpty()) throw Exception("Término de búsqueda demasiado corto")
+            val jsonString = response.body?.string().orEmpty()
+            val result = json.decodeFromString<ResponseDto>(jsonString)
+            if (result.mangaList.isEmpty()) throw Exception("No se han encontrado resultados.")
```
Comment (alessandrojean) [inline src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaOni.kt:159]: Just return an empty list instead, so the app can show the proper No results found error in the language the user uses the app.

```kotlin
return MangasPage(emptyList(), false)
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]
