### PR TITLE
Guya: parse description HTML and clean up code

### LINKED ISSUE #13418: Danke fürs Lesen: description containing html
### Source information and language

Danke fürs Lesen 1.3.3

### Steps to reproduce

Open any manga from the source and expand it's description.

### Expected behavior

The description shouldn't contain unrendered html

### Actual behavior

It contains unrendered html

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Screenshot_20220909-191931

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by stevenyomi**
Fixes #13418.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt [hunk 1]
```diff
@@ -36,22 +35,13 @@ abstract class Guya(
 
     private val scanlatorCacheUrl by lazy { "$baseUrl/api/get_all_groups/" }
 
-    override fun headersBuilder() = Headers.Builder().add(
```
Comment (AntsyLich) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt:39]: Any reason to remove this?

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt [hunk 2]
```diff
@@ -10,16 +10,13 @@ class GuyaGenerator : ThemeSourceGenerator {
 
     override val themeClass = "Guya"
 
-    override val baseVersionCode = 3
+    override val baseVersionCode = 4
 
     override val sources = listOf(
```
Comment (AntsyLich) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt:15]: sort thie items A-Z since you are touching the file

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt (hunk 1 above)
Comment (stevenyomi) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt:39]: There's no special reason to send a user agent to identify the app. IIRC arkon reviewed about this in a new extension PR. @arkon Any idea?

Comment (AntsyLich) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt:39]: Should be ok for friendlier sites since they won't use the ua to block tachi

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt (hunk 2 above)
Comment (stevenyomi) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt:15]: Is it necessary for 4 items?

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt (hunk 1 above)
Comment (arkon) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt:39]: We're okay with it if they ask for it purely for metrics purposes or something from their end. Guya's been friendly with us.
