### PR TITLE
MadTheme: fix pagination and relax rate limiting to CDN hosts

### LINKED ISSUE #11071: MangaMax
### Source information

MangaMax 1.2.4

### Steps to reproduce

1. Install MangaMax extension
2. Open MangaMax latest

### Expected behavior

Manga loads normally

### Actual behavior

1. Manga loads chapters and covers extremely slow (sometimes do not load at all)
2. In latest manga section, when scroll down for more latest updates, the manga looped
3. Latest manga updates way slower than webview

Screenshot_20220310-190308_Tachiyomi
Screenshot_20220310-190303_Tachiyomi

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

Webview loads normally and way faster

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #11071

Also disabled alternative CDNs as the current code required all 5 CDN hosts the be functional instead of any one of them. Maybe some fallback can be implemented in the future.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by arkon** [comment]
@mergifyio rebase

File: multisrc/overrides/madtheme/mangabuddy/src/MangaBuddy.kt [hunk 1]
```diff
@@ -11,6 +12,45 @@ class MangaBuddy : MadTheme(
     "en"
 ) {
     override val client: OkHttpClient = network.cloudflareClient.newBuilder()
-        .addInterceptor(RateLimitInterceptor(1, 2, TimeUnit.SECONDS))
+        .addInterceptor(
```
Comment (arkon) [inline multisrc/overrides/madtheme/mangabuddy/src/MangaBuddy.kt:15]: Any reason why you aren't just adding these in the main theme?

Comment (vetleledaal) [reply multisrc/overrides/madtheme/mangabuddy/src/MangaBuddy.kt:15]: I don't remember exactly, I think there was some kind of error cropping up when placing this in an abstract class.

I'll take a closer look tomorrow.

Comment (vetleledaal) [reply multisrc/overrides/madtheme/mangabuddy/src/MangaBuddy.kt:15]: It was actually the import for RateLimitInterceptor not being found. It works here since it's specified in MadTheme's default gradle file.

Do you know how to make this available from the multisrc context?

Comment (alessandrojean) [reply multisrc/overrides/madtheme/mangabuddy/src/MangaBuddy.kt:15]: Interceptors can only be added in overrides, it's the way multisrc is at the moment.
