### PR TITLE
Coffee Manga: fix lazy loaded pages

### LINKED ISSUE #17757: Coffee Manga: Pages after first do not load
### Source information

Coffee manga 1.4.32

### Source language

English

### Steps to reproduce

1. Select a manga
2. Open up chapter
3. Flip to next page
4. Next page does not load

### Expected behavior

1. Select a manga
2. Open up chapter
3. Flip to next page
4. Next page should load

### Actual behavior

Next page and all other pages other than the first do not load. 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

Downloading the chapter also does not show other pages. Using webview shows all pages. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #17757 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -68,7 +68,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Chibi Manga", "https://www.cmreader.info", "en", overrideVersionCode = 1),
         SingleLang("Clover Manga", "https://clover-manga.com", "tr", overrideVersionCode = 2),
         SingleLang("Coco Rip", "https://cocorip.net", "es"),
-        SingleLang("Coffee Manga", "https://coffeemanga.io", "en", overrideVersionCode = 1),
+        SingleLang("Coffee Manga", "https://coffeemanga.io", "en", isNsfw = false, overrideVersionCode = 2),
```
Comment (AntsyLich) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:71]:
```suggestion
        SingleLang("Coffee Manga", "https://coffeemanga.io", "en", overrideVersionCode = 2),
```

Comment (vetleledaal) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:71]: I think it's better to explicitly state that the site is not NSFW, so next time you know it has been checked previously.

Comment (AntsyLich) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:71]: mk
