### PR TITLE
EarlyManga: Fix chapter list parsing

### LINKED ISSUE #12192: Earlymanga Chapters Issue
### Source information

Earlymanga 1.2.17

### Steps to reproduce

Search up whatever manga, and click it. Check their site too see that it doesn't match. 

### Expected behavior

All manga shows and you can read it. 

### Actual behavior

Only one chapter shows and says page doesn't exist, despite going to the website for 100s of chapters ready to read. 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Apologies in advance to whoever reviews this. Followed the earlier trend of obfuscating stuff.
Closes #12192

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt [hunk 1]
```diff
@@ -112,31 +117,65 @@ class EarlyManga : ParsedHttpSource() {
     override fun chapterListParse(response: Response): List<SChapter> {
         var document = response.asJsoup()
         val chapters = mutableListOf<SChapter>()
-        var nextPage = 2
-        document.select(chapterListSelector()).map { chapters.add(chapterFromElement(it)) }
+
+        val crypt1 = (R.mipmap.ic_launcher ushr 87895464) * (456123 ushr 42) - 16 / 4 * -3
```
Comment (AntsyLich) [inline src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt:121]: This returns the app's logo so it might break in other forks

Comment (vetleledaal) [reply src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt:121]: I think this is just the extension icon, that's what shows in the IDE at least. Regardless, I've tested with TachiyomiJ2K and it works fine

Comment (AntsyLich) [reply src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt:121]: Resource stuff is not affected then. Noted.
