### PR TITLE
Fix WRT image could not be found

### LINKED ISSUE #12193: World romance translation: broken (Image could not be found)
### Source information

World romance translation 1.3.20

### Steps to reproduce

1. Choose any comic in the world romance translation extension.
2. choose a chapter (especially the new chapter), 
3. and it happens "image could not be found". Almost all comics there (world romance translation) have this problem, I've tried in webview but there Normal, nothing happens

Screenshot_20220614_133027
Screenshot_20220614_134751
Screenshot_20220614_140911

### Expected behavior

Normal as usual

### Actual behavior

"Image could not be found" Almost in all chapters, especially the new chapter

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

Screenshot_20220614_133027

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mxsgx**
I have tested in my android emulator and physical device, and it works.

Fix #12193

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/wpmangareader/worldromancetranslation/src/WorldRomanceTranslationImageInterceptor.kt [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package eu.kanade.tachiyomi.extension.id.worldromancetranslation
+
+import okhttp3.Interceptor
+import okhttp3.Response
+
+class WorldRomanceTranslationImageInterceptor : Interceptor {
+    override fun intercept(chain: Interceptor.Chain): Response {
+        return chain.proceed(
+            chain.request()
+                .newBuilder()
```
Comment (alessandrojean) [inline multisrc/overrides/wpmangareader/worldromancetranslation/src/WorldRomanceTranslationImageInterceptor.kt:10]: Just add the Referer header in the `headersBuilder` inside the source class. There's no need to use an interceptor just for this at all.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Review by alessandrojean — APPROVED** [review]
