### PR TITLE
MangaThemesia: AsuraScansEn search and ManhwaFreak dates

### LINKED ISSUE #18003: Incorrect Artist listed on Asura Scans Academy's Undercover Professor
### Source information

Asura Scans 1.4.52

### Source language

English

### Steps to reproduce

1. Open Academy's Undercover Professor in Asura Scans

### Expected behavior

The artist should show up as unknown, as there is no listed artist on the Asura Scans website

### Actual behavior

"Chapter 57 - Artist Pierre" shows up as the artist

### Tachiyomi version

Tachiyomi 0.14.6 Preview r6053

### Android version

Android 13

### Other details

Seems to be caused by accidentally finding the chapter title when searching the page for "artist"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by nzoba**
- Added cancelled status to multisrc. Didn't think it was worth to update all extensions
- ManhwaFreak: fix relative dates
- AsuraScans: fix search

Closes #18003

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt [hunk 1]
```diff
@@ -215,6 +214,7 @@ abstract class MangaThemesia(
         listOf("ongoing", "publishing").any { this.contains(it, ignoreCase = true) } -> SManga.ONGOING
         this.contains("hiatus", ignoreCase = true) -> SManga.ON_HIATUS
         this.contains("completed", ignoreCase = true) -> SManga.COMPLETED
+        listOf("dropped", "cancelled").any { this.contains(it, ignoreCase = true) } -> SManga.CANCELLED
```
Comment (Riztard) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt:217]: wouldnt some other source use this as well?
