### PR TITLE
Fix ReaperScans(BR) and YugenMangas(ES)

### LINKED ISSUE #17405: Reaper Scans (Portuguese): HTTP error 400
### Source information

Reaper scan 1.4.51

### Source language

Português (Brasil)

### Steps to reproduce

when entering the source gives error 400

### Expected behavior

Opening of the extension and exhibition of all works belonging to ascan.

### Actual behavior

when trying to enter the extension to look at the scan works, it presents the error shown, even with the webview working perfectly.

### Tachiyomi version

0.14.6

### Android version

10

### Other details

the scan site is working perfectly in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #17405

Can be moved to super class if other sources make the change.

New API not show latest updates (site issue), but chapters are updated.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/heancms/yugenmangas/src/YugenMangas.kt [hunk 1]
```diff
@@ -31,6 +42,82 @@ class YugenMangas :
...
+
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        val sortByFilter = filters.firstInstanceOrNull<SortByFilter>()
+        val statusFilter = filters.firstInstanceOrNull<StatusFilter>()
+
+        val tagIds = filters.firstInstanceOrNull<GenreFilter>()?.state
+            ?.filter(Genre::state)
+            ?.map(Genre::id)
+            .orEmpty()
+            .joinToString(prefix = "[", postfix = "]")
```
Comment (alessandrojean) [inline multisrc/overrides/heancms/yugenmangas/src/YugenMangas.kt:81]: Set the separator explicitly to `,` as the default includes a space.

```suggestion
        val tagIds = filters.firstInstanceOrNull<GenreFilter>()?.state.orEmpty()
            .filter(Genre::state)
            .map(Genre::id)
            .joinToString(",", prefix = "[", postfix = "]")
```

File: multisrc/overrides/heancms/reaperscans/src/ReaperScans.kt [hunk 2]
```diff
@@ -27,6 +38,82 @@ class ReaperScans : HeanCms(
...
+
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        val sortByFilter = filters.firstInstanceOrNull<SortByFilter>()
+        val statusFilter = filters.firstInstanceOrNull<StatusFilter>()
+
+        val tagIds = filters.firstInstanceOrNull<GenreFilter>()?.state
+            ?.filter(Genre::state)
+            ?.map(Genre::id)
+            .orEmpty()
+            .joinToString(prefix = "[", postfix = "]")
```
Comment (alessandrojean) [inline multisrc/overrides/heancms/reaperscans/src/ReaperScans.kt:77]:
```suggestion
        val tagIds = filters.firstInstanceOrNull<GenreFilter>()?.state.orEmpty()
            .filter(Genre::state)
            .map(Genre::id)
            .joinToString(",", prefix = "[", postfix = "]")
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]
