### PR TITLE
Bato.to: remove broken mirrors, add new mirrors

### LINKED ISSUE #17010: Bat.to
### Source information

Bat.to 1.4.31

### Source language

English 

### Steps to reproduce

1. Open
2. Wait

### Expected behavior

It should have work

### Actual behavior

java.net.connectException: Failed to connect to/

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #17010 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt [hunk 1]
```diff
@@ -938,35 +938,57 @@ open class BatoTo(
...
             "mto.to",
             "wto.to",
+            "xbato.com",
+            "xbato.net",
+            "xbato.org",
+            "zbato.com",
+            "zbato.net",
+            "zbato.org",
         )
         private val MIRROR_PREF_ENTRY_VALUES = arrayOf(
```
Comment (AntsyLich) [inline src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt:966]:
```suggestion
        private val MIRROR_PREF_ENTRY_VALUES = MIRROR_PREF_ENTRIES.map { "https://$it" }.toTypedArray()
```
