### PR TITLE
Gmanga / fix url

### LINKED ISSUE #10793: GManga some chapters are broken, HTTP error 103
### Source information

GManga 1.2.9

### Steps to reproduce

This is an intermittent issue, when connected to a server sending out HTTP 103 codes:
1. Open "National School Prince is a Girl"
2. Open chapter 237 OR 236 (others are not affected)

### Expected behavior

Pages load

### Actual behavior

Pages don't load

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Might be fixed by tachiyomiorg/tachiyomi#6623, but additional testing is required

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by zeredouni**
Closes #10860
Closes #10793

### CODE REVIEW

File: src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt [hunk 1]
```diff
@@ -109,7 +109,7 @@ class Gmanga : ConfigurableSource, HttpSource() {
 
                     thumbnail_url = it.jsonObject["cover"]!!.jsonPrimitive.contentOrNull?.let { coverFileName ->
                         val thumbnail = "medium_${coverFileName.substringBeforeLast(".")}.webp"
-                        "https://media.$domain/uploads/manga/cover/${it.jsonObject["id"]!!.jsonPrimitive.content}/$thumbnail"
+                        "https://media.gmanga.me/uploads/manga/cover/${it.jsonObject["id"]!!.jsonPrimitive.content}/$thumbnail"
```
Comment (CarlosEsco) [inline src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt:112]: why switch to .org but use .me for the media?

Comment (zeredouni) [reply src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt:112]: Because the Website is completely dependent on (.org) but used  (.me) to store media .
