### PR TITLE
ReaperScans: use absolute src to handle cloudflare mirage links

### LINKED ISSUE #13936: Reaper Scans (English): Some pages doesn't load
### Source information and language

Reaper scans 1.3.39

### Steps to reproduce

1) Open tachiyomi sy
2) search the reaper scans extension
3) open any manga
4) click on any chapter

### Expected behavior

Pages should be loaded as same as the webview. 

### Actual behavior

2 pages keeps on loading even if the rest of chapter is loaded.. These 2 pages are not existent in webview. 

Webview:
IMG_20221020_221333

In app:
IMG_20221020_221313

### Tachiyomi version

App version: 1.8.5 (standard, 57351c68d, 42, 2022-10-18T21:58Z) Preview build: 484 Android version: 12 (SDK 31) Android build ID: SKQ1.211006.001 test-keys Device brand: Xiaomi Device manufacturer: Xiaomi Device name: zeus Device model: 2201122G Device product name: zeus_in

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14248: Reaper Scans (English): Can't load any manga chapters
### Source information and language

Reaper Scans 1.3.39 EN

### Steps to reproduce

1. Open a random manga
2. Click on a chapter

### Expected behavior

Manga chapter should load

### Actual behavior

Nothing loads and only shows the number of pages the chapter has

Also it can't download any of the chapters. When a global update happens it will give this error:
Screenshot_20221114-104455

### Tachiyomi version

r5232

### Android version

Android 11

### Other details

Screenshot_20221113-213925

(When opening a webview I can just load the chapter pages)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AriaMoradi**
closes #14248
closes #13936 -> can be reproduced when setting an Android UserAgent

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 1]
```diff
@@ -276,7 +276,9 @@ class ReaperScans : ParsedHttpSource() {
     // Page
     override fun pageListParse(document: Document): List<Page> {
         return document.select("img.max-w-full").mapIndexed { index, element ->
-            Page(index, imageUrl = element.attr("src"))
+            val imageSrc = element.attr("src")!!
```
Comment (alessandrojean) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt:279]: Can just use `attr("abs:src")` instead.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Review by alessandrojean — APPROVED** [review]

**Comment by ArjixWasTaken** [comment]
+1
