### PR TITLE
MasterKomik changed to Tenshi.id

### LINKED ISSUE #15369: Masterkomik wrong chapter release date
### Source information and language

Masterkomik 1.4.25

### Steps to reproduce

1. Open masterkomik
2. Open any manga

### Expected behavior

The release date should be the same as on the website.

### Actual behavior

Screenshot_2023-02-16-19-45-47-688_eu kanade tachiyomi

Screenshot_2023-02-16-19-46-02-811_eu kanade tachiyomi

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #17625: MasterKomik: Changed their name & domain to Tenshi.id
### Source information

MasterKomik 1.4.27

### Source language

Indonesian

### Source new URL

https://tenshi.id/

### Other details

The old website will be discontinued at the end of this month

This information was obtained from the Discord channel of Masterkomik (now:Tenshi.id)
tenshi

Translate : "The website Masterkomik.com has changed its domain to Tenshi.id. Don't forget to move your bookmarks, okay :luvv:
@everyone
Always support us by Upvoting and Commenting!!"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by MuhamedZ1**
Changed icons, renamed extension, changed domain

Closes #15369
Closes #17625

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by mozzaru** [comment]
Didn't Masterkomik change its domain to this?
https://tenshi.id

**Comment by MuhamedZ1** [comment]
Yes i just checked it now, it was being redirected to https://tenshi.id/
should i just replace the website url or rename the entire extension?

And is this url change currently among any issue that i need to mention in pr body

**Comment by mozzaru** [comment]
Try to ask @Riztard 😁

File: multisrc/overrides/mangathemesia/masterkomik/src/TenshiId.kt [hunk 1]
```diff
@@ -3,8 +3,10 @@ package eu.kanade.tachiyomi.extension.id.masterkomik
 import eu.kanade.tachiyomi.multisrc.mangathemesia.MangaThemesia
 import eu.kanade.tachiyomi.network.interceptor.rateLimit
 import okhttp3.OkHttpClient
+import java.text.SimpleDateFormat
+import java.util.Locale
 
-class MasterKomik : MangaThemesia("MasterKomik", "https://masterkomik.com", "id") {
+class TenshiId : MangaThemesia("Tenshi.id", "https://tenshi.id", "id", dateFormat = SimpleDateFormat("MMMM dd, yyyy", Locale("id", "ID"))) {
```
Comment (alessandrojean) [inline multisrc/overrides/mangathemesia/masterkomik/src/TenshiId.kt:9]: Changing the name will make people need to migrate without need. Please follow the CONTRIBUTING.md guide on how to change names and keep the old ID to prevent unnecessary migrations.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Comment by alessandrojean** [comment]
Also, please do use the icon generator tool linked in the CONTRIBUTING.md guide. This one does not follow the pattern used by all other extensions (square with rounded corners).

**Review by alessandrojean — APPROVED** [review]
