### PR TITLE
Mangceh migrated to Mareceh

### LINKED ISSUE #10784: Mangceh: Changed their domain and theme
### Source information

Mangceh 1.2.18

### Steps to reproduce

1. Open extension http error 400
2. Open in web view change domain from https://mangceh.me/ to https://mareceh.com/

### Expected behavior

Manga not shown

### Actual behavior

Http Error 400

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by TheKingTermux**
* Removed Mangceh from Madara MultiSrc
* Added Mareceh to WPMangaStream MultiSrc
* Added Mareceh directory folder on WPMangaStream MultiSrc 
* Added Mareceh icon
* Added Mareceh.kt
* Deleted Old Mangceh directory folder on Madara MultiSrc 
* Updated Mareceh.kt
* Change Mangceh icon
//Updated
* Change directory folder name from mareceh to mangceh in override WPMangaStream directory 
* Migrate all file from mareceh directory to mangceh directory 

Closed #10784 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package eu.kanade.tachiyomi.extension.id.mareceh
+
+import eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor
+import eu.kanade.tachiyomi.multisrc.wpmangastream.WPMangaStream
+import okhttp3.OkHttpClient
+import java.util.concurrent.TimeUnit
+
+class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {
```
Comment (alessandrojean) [inline multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt:8]: Potentially the URL paths have changed and the old URLs are unsupported. If it's the case, please also bump the `versionId`.

```suggestion
class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {

    override val versionId = 2

```

**Review by alessandrojean — COMMENTED** [review]
Also remove the old override.

`multisrc/overrides/madara/mangceh/src/Mangceh.kt`

**Comment by TheKingTermux** [comment]
> 

Roger that

**Comment by alessandrojean** [comment]
Can you please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate the icons? So they follow the same pattern of the other extensions.

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt [hunk 2]
```diff
@@ -33,6 +33,7 @@ class WPMangaStreamGenerator : ThemeSourceGenerator {
         SingleLang("Manga Pro Z", "https://mangaprotm.com", "ar", overrideVersionCode = 1),
         SingleLang("Manga Raw.org", "https://mangaraw.org", "ja", className = "MangaRawOrg", overrideVersionCode = 1),
         SingleLang("MangaIndonesia", "https://mangaindonesia.net", "id"),
+        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 1),
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt:36]:
```suggestion
        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 10),
```

Needs to be `10` because the old one was `23` (Madara's `baseVersionCode = 20` + Mangceh's `overrideVersionCode 
 = 3`), and since WpMangaStream's `baseVersionCode = 14`, `baseVersionCode + overrideVersionCode` should be `24` to it be an update and new version.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Comment by TheKingTermux** [comment]
> Can you please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate the icons? So they follow the same pattern of the other extensions.

Okay
Im working on it

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt [hunk 3]
```diff
@@ -33,6 +33,7 @@ class WPMangaStreamGenerator : ThemeSourceGenerator {
         SingleLang("Manga Pro Z", "https://mangaprotm.com", "ar", overrideVersionCode = 1),
         SingleLang("Manga Raw.org", "https://mangaraw.org", "ja", className = "MangaRawOrg", overrideVersionCode = 1),
         SingleLang("MangaIndonesia", "https://mangaindonesia.net", "id"),
+        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 10),
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt:36]: Sorry about noticing it just now, but since the source changed its name, you need to keep the old package name, otherwise users will not receive any update to the existing extension. The `id` change in this case doesn't matter since the URLs are incompatible anyway.

```suggestion
        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, pkgName = "mangceh", overrideVersionCode = 10),
```

After changing it, move the overrides from the `multisrc/overrides/wpmangastream/mareceh` folder to `multisrc/overrides/wpmangastream/mangceh`.

After this last change, the PR will be good and can be merged 👍🏻

File: multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt [hunk 4]
```diff
@@ -0,0 +1,21 @@
+package eu.kanade.tachiyomi.extension.id.mareceh
```
Comment (alessandrojean) [inline multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt:1]: Remember to change the package inside the class too.

```suggestion
package eu.kanade.tachiyomi.extension.id.mangceh
```

File: multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+
+import eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor
+import eu.kanade.tachiyomi.multisrc.wpmangastream.WPMangaStream
+import okhttp3.OkHttpClient
+import java.util.concurrent.TimeUnit
+
+class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {
```
Comment (alessandrojean) [inline multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt:8]: Just a note: The class name should be let as it is now, i.e. can be kept as `Mareceh`. It's _only the package name_ that need to be the same as the old one.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt (hunk 3 above)
Comment (TheKingTermux) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt:36]: Ohh i see
Thanks for the updated 👍🏻
And I finally understood a new lesson from you.

File: multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt (hunk 5 above)
Comment (TheKingTermux) [reply multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt]: Roger that

File: multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt (hunk 4 above)
Comment (TheKingTermux) [reply multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt]: Roger

**Comment by alessandrojean** [comment]
Forgot to remove the `multisrc/overrides/wpmangastream/mareceh` folder as it is not used anymore (it has icons inside, delete them too).

**Comment by TheKingTermux** [comment]
> Forgot to remove the `multisrc/overrides/wpmangastream/mareceh` folder as it is not used anymore (it has icons inside, delete them too).

Sorry i forgot it deleting them 😅

**Review by alessandrojean — APPROVED** [review]

**Review by alessandrojean — APPROVED** [review]
