### PR TITLE
Multisrc Updates: WPMangaStream & Madara

### LINKED ISSUE #5994: [Source Request] <SISIGELAP Manhwa>
---

## Source website
- Name: SISIGELAP
- Link: https://sisigelap.club/
- Language(s): Indonesia/Bahasa Indonesia

## Other details
Manhwa

### LINKED ISSUE #5996: [Bug] <World Romance Translation>: <Http error 400>
## Device information
- Tachiyomi version: SY Preview r340
- Android version: 8.0

## Source information
- Name: World Romance Translation (Madara)
- Extension version: 1.2.1

## Steps to reproduce
1. Open source

### Expected behavior
List of manga appear

### Actual behavior
Http error 400

### PR DESCRIPTION
**Pull request by happywillow0**
Fixes #5996

- Moves World Romance Translation from Madara to WPMangaStream
- Updates date format

Not sure if there is a version code to increment. 
As far as I know, users will have to manually migrate to the new extension?

Closes #5994

- Adds SISI GELAP to Madara

### CODE REVIEW

**Comment by happywillow0** [comment]
Since I'm changing Madara, I'm looking into adding #5994

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt [hunk 1]
```diff
@@ -49,6 +49,7 @@ class WPMangaStreamGenerator : ThemeSourceGenerator {
             SingleLang("Tempest Manga", "https://manga.tempestfansub.com", "tr"),
             SingleLang("xCaliBR Scans", "http://xcalibrscans.com", "en"),
             SingleLang("NoxSubs", "https://noxsubs.com", "tr"),
+            SingleLang("World Romance Translation", "https://wrt.my.id/", "id"),
```
Comment (Riztard) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt:52]: i think need to add `overrideVersionCode = 1` like others even if it move theme

Comment (happywillow0) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt:52]: I'll add it in at some poin soon. My parents are over this weekend so I'm not sure when I'll be able to get to it.
