### PR TITLE
Mangaspw fix

### LINKED ISSUE #7154: [Bug] <Mangas.pw(Mangas.in)>: <Error in manga chapters>
## Device information
- Tachiyomi version: 1.0.17 (J2K)
- Android version: SAMSUNG, 7.0.1

## Source information
- Name: Mangas.pw(Mangas.in)
- Extension version: 1.2.3

## Steps to reproduce
1. Open extension section
2. Open sleeve (any)

### Expected behavior
Shows all the chapters to be shown in the sleeves without any error.

### Actual behavior
Only one chapter of all the sleeves is shown, and without having to do with them (changed chapters)

## Other details
- The extension is Spanish language
- Bug Images:
https://i.imgur.com/ZYApRVO.jpg
https://i.imgur.com/3v3KC3E.jpg
https://i.imgur.com/ovtSW1T.jpg

### PR DESCRIPTION
**Pull request by DTecheira**
This is a simple workaround

Fixes #7154

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSSources.kt [hunk 1]
```diff
@@ -33,7 +33,7 @@ class MMRCMSSources {
                 override val overrideVersionCode: Int = 0,
             ) : SourceData()
         }
-        val version: Int = 3
+        val version: Int = 4
```
Comment (DTecheira) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSSources.kt:36]: I am not sure if this version should be changed
