### PR TITLE
NineAnime: fix chapter pages

### LINKED ISSUE #13315: NineAnime: all_imgsurl not found
### Source information and language

NineAnime 1.3.3

### Steps to reproduce

1. Open manga from nineanime source
2. Open a chapter

### Expected behavior

Open chapter to read

### Actual behavior

Fails to open chapter with message all_imgsurl not found

### Tachiyomi version

Tachiyomij2k 1.5.8

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Renzo904**
Closes #13315

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt [hunk 1]
```diff
@@ -151,8 +158,14 @@ class NineAnime : ParsedHttpSource() {
     // Pages
 
     override fun pageListRequest(chapter: SChapter): Request {
+        val id: String = chapter.url.substring(chapter.url.lastIndexOf("/", chapter.url.length - 2))
+
         val pageListHeaders = headersBuilder().add("Referer", "$baseUrl/manga/").build()
-        return GET(baseUrl + chapter.url, pageListHeaders)
+        val response = client.newCall(GET("$pagesUrl/c/nineanime$id", pageListHeaders)).execute()
```
Comment (alessandrojean) [inline src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt:164]: The methods ending with `request` aren't supposed to do any network calls. Will need to refatorate to do any additional requests needed in the `pageListParse` method instead.

My tip is to make this function to return the first request you need and then in the `pageListParse` you call the second request and properly parse it.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt [hunk 2]
```diff
@@ -31,6 +32,8 @@ class NineAnime : ParsedHttpSource() {
         .followRedirects(true)
         .build()
 
+    val pagesUrl: String = "https://www.glanceoflife.com"
```
Comment (alessandrojean) [inline src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt:35]: Can be added to the `companion object` as a constant instead.

```kotlin
companion object {
    private const val PAGES_URL = "https://www.glanceoflife.com"
}
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Review by alessandrojean — APPROVED** [review]
