### PR TITLE
MangaPark v3: Fix chapter pages not loading

### LINKED ISSUE #12963: Mangapark giving JSON issue
### Source information and language

Mangapark

### Steps to reproduce

Open Mangapark
Select any chapter of any manga, manhwa, manhua, etc.

### Expected behavior

This shouldn't happen

### Actual behavior

When trying to read any Mangapark Chapter of anything, gives the message
Unexpected JSON Token at offset 17: Expected EOF after parsing, but had = instead JSON input: document.domain = 'mangapark.net'

### Tachiyomi version

0.13.5

### Android version

Android 7.0

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AntsyLich**
Also move to QuickJS

Fixes #12963

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt [hunk 1]
```diff
@@ -248,28 +248,24 @@ open class MangaPark(
...
+        val amPass = script.substringAfter("const amPass =").substringBefore(";").trim()
 
-        val imgWordLisRaw = Duktape.create().use { it.evaluate(decryptScript).toString() }
-        val imgWordLis = json.parseToJsonElement(imgWordLisRaw).jsonArray
+        val decryptScript = cryptoJS + "CryptoJS.AES.decrypt($amWord, $amPass).toString(CryptoJS.enc.Utf8);"
 
-        return imgWordLis.mapIndexed { i, imgWordE ->
-            val imgPath = imgPathLis[i].jsonPrimitive.content
-            val imgWord = imgWordE.jsonPrimitive.content
+        val imgAccListString = Duktape.create().use { it.evaluate(decryptScript).toString() }
```
Comment (alessandrojean) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt:264]: Maybe already switch to QuickJS too?

Comment (AntsyLich) [reply src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt:264]: No wonder i felt that i missed something.
