### PR TITLE
Manga1st: Fix only first page loading

### LINKED ISSUE #10056: Manga1st chapters only load one page
### Source information

Manga1st 1.2.15

### Steps to reproduce

In Manga1st extension open any manhua with new chapters and open the new chapter

### Expected behavior

When you open a new chapter it should load all chapter pages

### Actual behavior

 when you open a new chapter it only loads the first page

### Tachiyomi version

0.12.3

### Android version

Androis 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Troy121**
Closes #10056

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -181,7 +181,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Manga-Online.co", "https://www.manga-online.co", "th", className = "MangaOnlineCo"),
         SingleLang("Manga-Scantrad", "https://manga-scantrad.net", "fr", className = "MangaScantrad", overrideVersionCode = 2),
         SingleLang("Manga18 Fx", "https://manga18fx.com", "en", overrideVersionCode = 1),
-        SingleLang("Manga1st", "https://manga1st.com", "en", overrideVersionCode = 1),
+        SingleLang("Manga1st", "https://manga1st.com", "en", className = "Manga1st", overrideVersionCode = 2),
```
Comment (Riztard) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:184]: no need to add className
