### PR TITLE
Comick.fun: Code rewritten

### LINKED ISSUE #12916: Comick.fun: Unexpected 'null' when string was expected when using Latest on All & English
### Source information and language

Comick.fun 1.3.12 (English & All)

### Steps to reproduce

1. Browse sources
2. Find Comick.fun sources (either All or English)
3. Click on **Latest**

### Expected behavior

Tachiyomi would load up Comick.fun's latest updated manga

### Actual behavior

Unexpected 'null' when string was expected

### Tachiyomi version

0.13.5

### Android version

Android 9

### Other details

This seems to only on English & All
I have tried replicating the same steps on Indonesia, Deutsch, Catala, and espanol which works just fine.

side note: Reinstalling the Comick.fun's extension does not fix the issue for me. I have also reported it to Comick's dev, and he told me to reach out to tachiyomi instead

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by sergiomalagon**
… the way for future upgrades

Closes #12916

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 1]
```diff
@@ -1,450 +1,323 @@
...
-        if (!query.startsWith(SLUG_SEARCH_PREFIX))
-            return super.fetchSearchManga(page, query, filters)
-
-        // deeplinking
-        val potentialUrl = "/comic/${query.substringAfter(SLUG_SEARCH_PREFIX)}"
-        return fetchMangaDetails(SManga.create().apply { this.url = potentialUrl })
-            .map { MangasPage(listOf(it.apply { this.url = potentialUrl }), false) }
-            .onErrorReturn { MangasPage(emptyList(), false) }
+    override fun popularMangaRequest(page: Int): Request {
+        return client.newCall(
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:65]: You can just return the GET directly, doesn't need to use the client for that at all.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 2]
```diff
@@ -1,450 +1,323 @@
...
-        .let { MangasPage(it, it.size == SEARCH_PAGE_LIMIT) }
-
-    /** Manga Details **/
-
-    private fun apiMangaDetailsRequest(manga: SManga): Request {
-        return GET("$apiBase/comic/${slug(manga)}", headers)
+    /** Latest Manga **/
+    override fun latestUpdatesRequest(page: Int): Request {
+        return client.newCall(
+            GET(
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:96]: Same here and in other similar places.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 3]
```diff
@@ -1,450 +1,323 @@
...
-                    .mapIndexed { index, it -> index to it }
-                    .filterNot { (index, _) -> this.state[index].isIgnored() }
-                    .partition { (index, _) -> this.state[index].isIncluded() }
-                    .let { (included, excluded) ->
-                        included.asSequence().map { it.second } to excluded.asSequence().map { it.second }
-                    }
-            }
+    /** Manga Chapter List **/
+    override fun chapterListRequest(manga: SManga): Request {
+        val mangaDataRequest = client.newCall(
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:250]: Although it's acceptable, it's better to just return the request in the request methods and do additional network calls in the parse methods.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 4]
```diff
@@ -1,450 +1,323 @@
...
-        LabeledValue("High rating", "rating"),
-        LabeledValue("Last updated", "uploaded")
-    )
-
     companion object {
         const val SLUG_SEARCH_PREFIX = "id:"
     }
+
+    /** Don't touch this, Tachiyomi forces you to declare the following methods even I you don't use them **/
+    override fun imageUrlParse(response: Response): String {
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:320]: Alternatively you can just return a empty string since it won't even be called.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 5]
```diff
@@ -1,450 +1,323 @@
...
+        val mangaDataRequest = client.newCall(
+            GET(
+                "$API_BASE${manga.url}".toHttpUrl().newBuilder().apply {
+                    addQueryParameter("tachiyomi", "true")
+                }.build().toString(),
+                headers, CacheControl.FORCE_NETWORK
+            )
+        ).execute()
+
+        val mangaData = JSONObject(mangaDataRequest.body!!.string())
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:259]: Use kotlinx-serialization's `Json` instance please, since you're also using it with the DTOs. Don't use more than one parser.

Same for the other JSONObject usages.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 6]
```diff
@@ -1,450 +1,323 @@
...
+        val mangaData = json.decodeFromString<MangaDetails>(response.body!!.string())
+        return SManga.create().apply {
+            title = mangaData.comic.title
+            artist = mangaData.artists.joinToString { it.name.trim() }
+            author = mangaData.authors.joinToString { it.name.trim() }
+            description = helper.beautifyDescription(mangaData.comic.desc)
+            genre = mangaData.genres.joinToString { it.name.trim() }
+            status = helper.parseStatus(mangaData.comic.status)
+            thumbnail_url = mangaData.comic.cover_url
+            initialized = true
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:244]: You can consider moving this to a `toSManga()` function inside `MangaDetails` and making the fields `private`. Same for other DTOs if applicable.

Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:244]: You can consider moving this to a `toSManga()` function inside `MangaDetails` and making the fields `private`. Same for other DTOs if applicable.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt [hunk 7]
```diff
@@ -0,0 +1,182 @@
+package eu.kanade.tachiyomi.extension.all.comickfun
+
+import eu.kanade.tachiyomi.source.model.Filter
+import eu.kanade.tachiyomi.source.model.FilterList
+
+class ComickFunFilters() {
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt:6]:
```suggestion
```

You don't need to wrap these with a class. Put them in the top level.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt [hunk 8]
```diff
@@ -0,0 +1,40 @@
+package eu.kanade.tachiyomi.extension.all.comickfun
+
+import android.os.Build
+import android.text.Html
+import eu.kanade.tachiyomi.source.model.SManga
+import org.jsoup.Jsoup
+
+class ComickFunHelper {
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt:8]:
```suggestion
```
Same here.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+            if (vol.isNotEmpty()) {
+                if (chap.isEmpty()) append("Volume $vol") else append("Vol. $vol")
+            }
+            if (chap.isNotEmpty()) {
+                if (vol.isEmpty()) append("Chapter $chap") else append(", Ch. $chap")
+            }
+            if (title.isNotEmpty()) {
+                if (chap.isEmpty()) append(title) else append(": $title")
+            }
+        }.toString()
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt:38]:
```suggestion
        return buildString {
            if (vol.isNotEmpty()) {
                if (chap.isEmpty()) append("Volume $vol") else append("Vol. $vol")
            }
            if (chap.isNotEmpty()) {
                if (vol.isEmpty()) append("Chapter $chap") else append(", Ch. $chap")
            }
            if (title.isNotEmpty()) {
                if (chap.isEmpty()) append(title) else append(": $title")
            }
        }
```

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 10]
```diff
@@ -1,450 +1,323 @@
...
-                            if (cp.size == SEARCH_PAGE_LIMIT)
-                                getAllPagesFrom(page + 1, pred = pred.concatWith(Observable.just(cp))) // tail call to avoid blowing the stack
-                            else // by the pigeon-hole principle
-                                pred.concatWith(Observable.just(cp))
+    /** Manga Search **/
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        val url: String = API_BASE.toHttpUrl().newBuilder().apply {
+            addPathSegment("search")
+            if (query.isEmpty()) {
+                filters.forEach { it ->
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:129]: You can move the filter parsing logic to a separate function in `ComickFunFilters.kt`.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 11]
```diff
@@ -1,450 +1,323 @@
...
-            .onErrorReturn { MangasPage(emptyList(), false) }
+    override fun popularMangaRequest(page: Int): Request {
+        return client.newCall(
+            GET(
+                API_BASE.toHttpUrl().newBuilder().apply {
+                    addPathSegment("search")
+                    addQueryParameter("sort", "user_follow_count")
+                    addQueryParameter("page", "$page")
+                    addQueryParameter("tachiyomi", "true")
+                }.build().toString(),
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:72]:
```suggestion
                }.toString(),
```
Same for other builders.

Also, there's nothing to escape here, so you can just use string template.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 12]
```diff
@@ -1,450 +1,323 @@
...
+                headers, CacheControl.FORCE_NETWORK
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:73]:
```suggestion
                headers
```
You don't need to force network unless the website's cache control is glitchy. Same for other places.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 13]
```diff
@@ -1,450 +1,323 @@
 package eu.kanade.tachiyomi.extension.all.comickfun
 
+// TODO: Hacer una prueba de descargar un manga entero y que se pueda leer sin problemas
```
Comment (stevenyomi) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:3]: Please use English.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 3 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:250]: This one has to be like that, I need chapter_count on the request

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 13 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 12 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 11 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt (hunk 9 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt (hunk 8 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt (hunk 7 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 5 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 4 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:301]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 3 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

**Review by alessandrojean — CHANGES_REQUESTED** [review]
Seems okay to me now, just do this missing change and it will be good.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 14]
```diff
@@ -1,450 +1,304 @@
...
+                    addQueryParameter("lang", comickFunLang)
+                    addQueryParameter(
+                        "limit", mangaData.comic.chapter_count.toString()
+                    )
+                }.toString(),
+                headers
+            )
+        ).execute()
+        val result = json.decodeFromString<ChapterList>(chapterData.body!!.string())
+        if (result.chapters.isEmpty()) return listOf(SChapter.create())
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:256]: Why are you returning a empty chapter? You are supposed to return a empty list

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 15]
```diff
@@ -237,50 +224,46 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
...
+        ).execute()
+        val result = json.decodeFromString<ChapterList>(chapterData.body!!.string())
         if (result.chapters.isEmpty()) return listOf(SChapter.create())
         return result.chapters.map { chapter ->
             SChapter.create().apply {
                 url = chapter.hid
-                name = helper.beautifyChapterName(chapter.vol, chapter.chap, chapter.title)
+                name = beautifyChapterName(chapter.vol, chapter.chap, chapter.title)
                 date_upload =
                     SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZZZZ").parse(chapter.created_at)!!.time
```
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:268]: You're talking about the function, right?

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 16]
```diff
@@ -1,450 +1,304 @@
...
+        ).execute()
+        val result = json.decodeFromString<ChapterList>(chapterData.body!!.string())
+        if (result.chapters.isEmpty()) return listOf(SChapter.create())
+        return result.chapters.map { chapter ->
+            SChapter.create().apply {
+                url = chapter.hid
+                name = beautifyChapterName(chapter.vol, chapter.chap, chapter.title)
+                date_upload =
+                    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZZZZ").parse(chapter.created_at)!!.time
+                chapter_number = if (chapter.chap.isEmpty()) 0F else chapter.chap.toFloat()
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:262]: Don't assign a chapter number if one isn't provided. The app will handle it if you don't provide one.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 17]
```diff
@@ -1,450 +1,304 @@
...
+                scanlator =
+                    if (chapter.group_name.isEmpty().not()) chapter.group_name[0] else "unknown"
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:264]:
```kt
chapter.group_name.joinToString().takeUnless { it.isBlank() }
```

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 18]
```diff
@@ -1,450 +1,304 @@
...
+                    )
+                }.toString(),
+                headers
+            )
+        ).execute()
+        val result = json.decodeFromString<ChapterList>(chapterData.body!!.string())
+        if (result.chapters.isEmpty()) return listOf(SChapter.create())
+        return result.chapters.map { chapter ->
+            SChapter.create().apply {
+                url = chapter.hid
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:259]: Build a proper path don't just keep the id. Some fork has option to directly open chapter with WebView.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 15 above)
[the remark this answers is not in the document]
Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:268]: No, the SimpleDateFormat instance, it should be a constant.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 19]
```diff
@@ -1,450 +1,304 @@
...
-    private fun MinChaptersFilter() = object : Filter.Text("Minimum Chapters", ""), UrlEncoded {
-        override fun encode(url: HttpUrl.Builder) {
-            if (state.isBlank()) return
-            state.toIntOrNull()?.takeUnless { it < 0 }?.let {
-                url.addQueryParameter("minimum", "$it")
-            } ?: throw RuntimeException("Minimum must be an integer greater than 0")
+    override fun pageListParse(response: Response): List<Page> {
+        val result = json.decodeFromString<PageList>(response.body!!.string())
+        if (result.chapter.images.isEmpty()) return listOf()
+        return result.chapter.images.mapIndexed { index, data ->
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:283]: You did this every time but if you are gonna use map or it's variant then no need to check if the list is empty and returning a empty list

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt [hunk 20]
```diff
@@ -12,7 +12,6 @@ val legacyLanguageMappings = mapOf(
 
 class ComickFunFactory : SourceFactory {
     override fun createSources(): List<Source> = listOf(
-        "all",
```
Comment (AntsyLich) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt:15]: Was "all" lang removed from site too? If not then keep it in tachi too

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 15 above)
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 21]
```diff
@@ -1,450 +1,323 @@
...
-import uy.kohesive.injekt.api.get
+import org.json.JSONObject
+import java.text.SimpleDateFormat
+import java.util.concurrent.TimeUnit
 
-const val SEARCH_PAGE_LIMIT = 100
+const val API_BASE = "https://api.comick.fun"
+
+abstract class ComickFun(override val lang: String, private val comickFunLang: String) :
+    HttpSource() {
```
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:24]: Irrelevant, blame Android Studio Formatter

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 18 above)
Comment (stevenyomi) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:259]: Should keep the old format if possible: `"${manga.url}/$hid-chapter-$chap-$iso639_1"` (read the deserializer code for meaning)

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 22]
```diff
@@ -1,450 +1,323 @@
...
 
-    private val mangaIdCache = SMangaDeserializer.mangaIdCache
+    override val supportsLatest = true
 
-    final override fun headersBuilder() = Headers.Builder().apply {
-        add("User-Agent", "Tachiyomi " + System.getProperty("http.agent"))
+    private val json = Json {
+        ignoreUnknownKeys = true
+        isLenient = true
+        prettyPrint = true
```
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:35]: Doesn't affect, I will remove it in future updates

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 23]
```diff
@@ -1,450 +1,323 @@
...
+        add("User-Agent", "Tachiyomi ${System.getProperty("http.agent")}")
     }
 
-    /** Returns an identifier referred to as `hid` for chapter **/
-    private fun hid(chapter: SChapter) = "$baseUrl${chapter.url}".toHttpUrl().pathSegments[2].substringBefore("-")
+    override val client: OkHttpClient = network.client.newBuilder().apply {
+        rateLimit(
+            4, 1, TimeUnit.SECONDS
+        )
+    }.build()
```
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:50]: Irrelevant

[the remark this answers is not in the document]
Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:50]: The code suggested by Lich is much more readable.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt (hunk 20 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt:15]: Not necessary, no one wants to open a manga and having 800+ chapters in every language

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 23 above)
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:50]: Arguably, but it doesn't affect

[the remark this answers is not in the document]
Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:50]: Yeah, but readability is always appreciated.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 22 above)
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 23 above)
[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 14 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 16 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 17 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 19 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:271]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt (hunk 20 above)
Comment (Riztard) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt:15]: some multi lang people might use it tho

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 24]
```diff
@@ -1,450 +1,284 @@
...
-        if (response.code == 204)
-            return noResults
-        return json.decodeFromString<List<SManga>>(
-            deserializer = ListSerializer(deepSelectDeserializer("md_comics")),
-            response.body!!.string()
-        ).let { MangasPage(it, true) }
-    }
+    override fun getFilterList() = FilterList(
+        getFilters()
+    )
```
Comment (Riztard) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:48]: maybe put this in the correct order / near the previous one for better diff

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 18 above)
Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:249]: Yeah, keep the old URL format, otherwise existing users will get a lot of "new" chapters when refreshing the library after the extension update.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 25]
```diff
@@ -253,15 +244,13 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
...
-        if (result.chapters.isEmpty()) return listOf(SChapter.create())
         return result.chapters.map { chapter ->
             SChapter.create().apply {
                 url = chapter.hid
                 name = beautifyChapterName(chapter.vol, chapter.chap, chapter.title)
                 date_upload = DATE_FORMATTER.parse(chapter.created_at)!!.time
-                chapter_number = if (chapter.chap.isEmpty()) 0F else chapter.chap.toFloat()
-                scanlator =
-                    if (chapter.group_name.isEmpty().not()) chapter.group_name[0] else "unknown"
+                chapter_number = chapter.chap.toFloat()
```
[the remark this answers is not in the document]
Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:252]: What Lich said, but if you really really want to provide it, do it like this

```suggestion
                chapter_number = chapter.chap.toFloatOrNull() ?: -1f
```

[the remark this answers is not in the document]
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

**Comment by sergiomalagon** [comment]
@alessandrojean I think it's all good now, let me know if I need to change anything more

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 26]
```diff
@@ -246,21 +245,25 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
         val result = json.decodeFromString<ChapterList>(chapterData.body!!.string())
         return result.chapters.map { chapter ->
             SChapter.create().apply {
-                url = chapter.hid
+                url = baseUrl.toHttpUrl().newBuilder().apply {
+                    addPathSegment("comic")
+                    addPathSegment(mangaData.comic.slug)
+                    addPathSegment("${chapter.hid}-chapter-${chapter.chap}-$comickFunLang")
+                }.toString()
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:252]: The chapter url should not contain the baseUrl. Also no need to use the Url builder as there are no query parameters to be sanitized and escaped.

```kotlin
url = "/comic/${mangaData.comic.slug}/${chapter.hid}-chapter-${chapter.chap}-$comickFunLang"
```

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 27]
```diff
@@ -246,21 +245,25 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
...
                 date_upload = DATE_FORMATTER.parse(chapter.created_at)!!.time
-                chapter_number = chapter.chap.toFloat()
                 scanlator = chapter.group_name.joinToString().takeUnless { it.isBlank() }
             }
         }
     }
 
     /** Chapter Pages **/
     override fun pageListRequest(chapter: SChapter): Request {
+        val chapterHid = chapter.url.split("/").last().split("-").first()
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:262]: You can do it like this to avoid splitting it.

```kotlin
val chapterHid = chapter.url.substringAfterLast("/").substringBefore("-")

**Review by alessandrojean — CHANGES_REQUESTED** [review]
Just found these two issues for now, rest (probably) should be fine.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 26 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 27 above)
Comment (sergiomalagon) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: Done

**Review by alessandrojean — APPROVED** [review]
