### PR TITLE
IU: descramble images

### LINKED ISSUE #11214: Immortal Updates: Chapter images are scrambled or do not load
### Source information

Immortal Updates 1.2.19

### Steps to reproduce

1. Opening the chapter
2. Waiting for it to load.
3. The first page didn't show up, and the rest of the pages has broken images.

### Expected behavior

The chapter should load with normal, colored pages.

### Actual behavior

The first page didn't load, second page an announcement from Immortal Updates to read from their website, third page and the rest showing broken images.

### Tachiyomi version

0.13.1

### Android version

Android 8.1.0

### Other details

This is how it's shown in "Empress' Harem" chapter 282. The previous chapter, 281, looks normal.

Screenshot_2022-03-23-03-34-58-006_eu kanade tachiyomi
Screenshot_2022-03-23-03-34-51-753_eu kanade tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beerpiss**
msedge_GbgXtYPu5j

Closes #11214 

Checklist:
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/madara/immortalupdates/src/ImmortalUpdates.kt [hunk 1]
```diff
@@ -1,7 +1,201 @@
...
+        val body = image.toResponseBody("image/jpeg".toMediaTypeOrNull())
+        return@addInterceptor response.newBuilder()
+            .body(body)
+            .build()
+    }.build()
+
+    override fun pageListParse(document: Document): List<Page> {
+        val pageList = super.pageListParse(document).toMutableList()
+
+        val unscramblingCallsUrl = pageList.firstOrNull { it.imageUrl!!.contains("00-call") }?.imageUrl
```
Comment (vetleledaal) [inline multisrc/overrides/madara/immortalupdates/src/ImmortalUpdates.kt:43]: Not consistent with line 63. The site's approach would be preferable, but any is fine here as long as it's consistent.
