### PR TITLE
Alceascan: fix error 404

### LINKED ISSUE #15442: Alceascans error
### Source information and language

Alceascans 1.4.1

### Steps to reproduce

Opened the extension and was told to open into webview mode

### Expected behavior

Error

### Actual behavior

Hopefully it's fixed

### Tachiyomi version

0.14.5

### Android version

Android 10 

### Other details

Screenshot_20230222-094240020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Riztard**
-moving from zManga theme to wpMangaThemesia theme 
-update icons
-add some rate limit

Closes #15442

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/mangathemesia/alceascan/src/Alceascan.kt [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package eu.kanade.tachiyomi.extension.id.alceascan
+
+import eu.kanade.tachiyomi.multisrc.mangathemesia.MangaThemesia
+import eu.kanade.tachiyomi.network.interceptor.rateLimit
+import okhttp3.OkHttpClient
+
+class Alceascan : MangaThemesia("Alceascan", "https://alceascan.my.id", "id") {
+
```
Comment (alessandrojean) [inline multisrc/overrides/mangathemesia/alceascan/src/Alceascan.kt:8]: Bump the `versionId` as the URL path structure is different through the themes? In this way users will be forced to migrate to update the URLs of their entries.

Comment (Riztard) [reply multisrc/overrides/mangathemesia/alceascan/src/Alceascan.kt:8]: ah right thats new things

Comment (Riztard) [reply multisrc/overrides/mangathemesia/alceascan/src/Alceascan.kt:8]: maybe need to be added to the checklist
