### PR TITLE
Removed QuegnaReader - Fixed TuttoAnimeManga

### LINKED ISSUE #9200: TuttoAnimeManga - No Chapters found, changed layout
### Source information

tuttoanimemanga 1.2.3

### Steps to reproduce

1. Open any entry from the sleepy translations extension
2. Refresh

### Expected behavior

Chapter list should show up

### Actual behavior

Chapter list does not show up

### Tachiyomi version

0.12.2-3812

### Android version

11

### Other details

Since two weeks the layout is in the same style as tachiyomi-it.gto-v1.2.4, which works perfectly on tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #9574: The extention TuttoAnimeManga don't work
### Source information

TuttoAnimeManga

### Steps to reproduce

When I try to refresh the page this happens: 
image

### Expected behavior

bug

### Actual behavior

bug

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #10884: TuttoAnimeManga not working
### Source information

TuttoAnimeManga 1.2.3

### Steps to reproduce

Simply is not working.

### Expected behavior

A list of manga should appear, and also the saved manga should works.

### Actual behavior

But nothing. "No results found"

### Tachiyomi version

0.13.1

### Android version

11

### Other details

Sorry, but now i can't upload img. But i think is not important. Black screen and "no results found" when you open the extension.

I think TuttoAnimeManga staff updated the site, so the extension doesn't work anymore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ReLoia**
Removed QuegnaReader - because they moved to Mangadex
Moved TuttoAnimeManga from `multisrc/overrides/foolslide` to `multisrc/overrides/pizzareader`
  \\-> Modified PizzaReader.kt to make TuttoAnimeManga work with it

Closes #10884
Closes #9574
Closes #9200

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/pizzareader/PizzaReaderGenerator.kt [hunk 1]
```diff
@@ -16,6 +16,7 @@ class PizzaReaderGenerator : ThemeSourceGenerator {
         SingleLang("Phoenix Scans", "https://www.phoenixscans.com", "it", className = "PhoenixScans", overrideVersionCode = 4),
         SingleLang("GTO The Great Site", "https://reader.gtothegreatsite.net", "it", className = "GTO", overrideVersionCode = 3),
         SingleLang("LupiTeam", "https://lupiteam.net", "it", overrideVersionCode = 3),
+        SingleLang("TuttoAnimeManga", "https://tuttoanimemanga.net", "it", overrideVersionCode = 1)
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/pizzareader/PizzaReaderGenerator.kt:19]:
```suggestion
        SingleLang("TuttoAnimeManga", "https://tuttoanimemanga.net", "it", overrideVersionCode = 4)
```

Needs to be `4` so the new version is higher, and the users receive the update.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/pizzareader/PizzaReader.kt [hunk 2]
```diff
@@ -31,8 +30,10 @@ abstract class PizzaReader(
 
     open val apiUrl by lazy { "$baseUrl$apiPath" }
 
-    protected open val json: Json by injectLazy()
-
+    protected open val json = Json {
```
Comment (arkon) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/pizzareader/PizzaReader.kt:33]: Would this affect the other sources for this generator at all? Should the `baseVersionCode` be bumped?
