### PR TITLE
The Property of Hate: fix webview URL

### LINKED ISSUE #10017: The Property Of Hate WebView URL duplicates its baseUrl
### Source information

The Property Of Hate 1.2.3

### Steps to reproduce

1. Install The Property Of Hate extension
2. Open the extension and select the singular entry
3. Tap the WebView button
4. Get error that `http://jolleycomics.comhttp://jolleycomics.com` could not be loaded (`net::ERR_NAME_NOT_RESOLVED`)

### Expected behavior

The WebView should be opened with a valid webpage (either Page 1, the recentmost page, or the homepage)

### Actual behavior

The WebView displays a `net::ERR_NAME_NOT_RESOLVED` error for the URL `http://jolleycomics.comhttp://jolleycomics.com` because the URL it tries to display duplicates the URL of the website

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

- When in the Source view (not the manga view), the WebView button in the top right corner works as expected and displays the homepage.
- I'm guessing that is might have something to do with how the singular Manga entry is built in the extension file, which already contains the full URL, but I'm not sure

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Fixed #10017, cleaned up the code, and upgraded to `https`.

I'm not sure if I ought to bump the `versionId` for the protocol change.
Existing entries should still work properly with their current `http` URL.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/thepropertyofhate/src/eu/kanade/tachiyomi/extension/en/thepropertyofhate/ThePropertyOfHate.kt [hunk 1]
```diff
@@ -12,104 +12,92 @@ import okhttp3.Request
 import okhttp3.Response
 import rx.Observable
 
-/**
- *  @author Aria Moradi <aria.moradi007@gmail.com>
- */
-
+/** @author Aria Moradi <aria.moradi007@gmail.com> */
```
Comment (CarlosEsco) [inline src/en/thepropertyofhate/src/eu/kanade/tachiyomi/extension/en/thepropertyofhate/ThePropertyOfHate.kt:15]: you can remove this

Comment (ObserverOfTime) [reply src/en/thepropertyofhate/src/eu/kanade/tachiyomi/extension/en/thepropertyofhate/ThePropertyOfHate.kt:15]: Let the guy have his credit. :(
