### PR TITLE
Picacomic: Fix json decoding error of non-ASCII chars (#19434)

### LINKED ISSUE #19434: "bad base-64"is displayed in PicaComic
### Source information

PicaComic 1.4.3

### Source language

zh

### Steps to reproduce

1.更新picacomic
2.打开picacomic即复现

### Expected behavior

没更新之前可以正常加载

### Tachiyomi version

0.14.7

### Android version

android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by fumiama**
Closes #19434
Caused by #19400

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

I have no condition to test because the repo is too heavy, but it can work theoretically for its just a small change.

### CODE REVIEW

File: src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt [hunk 1]
```diff
@@ -100,7 +100,7 @@ class Picacomic : HttpSource(), ConfigurableSource {
             )
         }
 
-        val payload = parts[1]?.let { JSONObject(String(Base64.decode(it, Base64.DEFAULT))) }
+        val payload = parts[1]?.let { JSONObject(Base64.decode(it, Base64.DEFAULT).decodeToString()) }
```
Comment (alessandrojean) [inline src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt:103]: While you're into it, if you can remove the `org.json` usages in favor of `kotlinx.serialization` (as the extension already uses in other places and even has a `Json` instance), it would be better. It's not a good practice to mix two parsers.

Comment (fumiama) [reply src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt]: That's all right.

**Review by fumiama — COMMENTED** [review]
Modified.

**Comment by drelover** [comment]
I have updated the new version，but the  same problem still exist.

**Comment by fumiama** [comment]
> I have updated the new version，but the  same problem still exist.

Yes, I have also updated and the same error occurs again. Maybe we should refer to some other parts. The newly introduced json lib may be a possible reason.
I am quite sure that this problem is caused by this line, because there is a symptom that when you reinstall it completely, the problem fixed for the first time and then occurred again.

**Comment by alessandrojean** [comment]
>  The newly introduced json lib may be a possible reason

No as the line modified in particular doesn't even use kotlinx.serialization, it is still using the old `org.json.JSONObject`, which should be already replaced at this point.

**Comment by fumiama** [comment]
> Please do follow the PR checklist next time and compile locally and test before submitting new untested PRs.

OK. Maybe it will cost me a few days or weeks to install all the environments so I will left this problem to someone else who would like to fix.
May my thoughts mentioned above help you.
