### PR TITLE
KumaPoi: change domain fix

### LINKED ISSUE #16825: Kumapoi: Changed their domain
### Source information

KumaPoi 1.4.25

### Source language

Indonesia 

### Source new URL

https://kumapoi.club/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by OdisBy**
Closes #16825 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt [hunk 1]
```diff
@@ -56,7 +56,7 @@ class MangaThemesiaGenerator : ThemeSourceGenerator {
         SingleLang("KomikIndo.co", "https://komikindo.co", "id", className = "KomikindoCo", overrideVersionCode = 3),
         SingleLang("KomikMama", "https://komikmama.co", "id", overrideVersionCode = 1),
         SingleLang("KomikManhwa", "https://komikmanhwa.me", "id", isNsfw = true),
-        SingleLang("KumaPoi", "https://kumapoi.me", "id", isNsfw = true),
+        SingleLang("KumaPoi", "https://kumapoi.club/", "id", isNsfw = true, overrideVersionCode = 2),
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt:59]: Remove the trailing slash.

```suggestion
        SingleLang("KumaPoi", "https://kumapoi.club", "id", isNsfw = true, overrideVersionCode = 2),
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]
