### PR TITLE
MangaDex use translatedLanguage and an alt cover

### LINKED ISSUE #7179: [Bug] Mangadex: Language filters not working
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.113

## Steps to reproduce
1. Have a mangadex chapter
2. Manually reload chapters

### Expected behavior
Only show chapters in the designated language

### Actual behavior
All chapters, in all languages are shown

## Other details
Saw in:
* Kumo desu ga, Nani ka?
* Tensei shittara slime Datta ken
* And all other manga ported from the old mangadex extension

### PR DESCRIPTION
**Pull request by CarlosEsco**
dex currently still hasnt populated cover api so couldnt verify it
https://api.mangadex.org/cover

Fixes #7179

### CODE REVIEW

File: src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt [hunk 1]
```diff
@@ -10,12 +10,14 @@ object MDConstants {
...
     val mangaLimit = 25
+    val cdnUrl = "https://uploads.mangadex.org"
+
     val apiUrl = "https://api.mangadex.org"
     val apiMangaUrl = "$apiUrl/manga"
     val atHomePostUrl = "https://api.mangadex.network/report"
     val whitespaceRegex = "\\s".toRegex()
 
-    val tempCover = "https://i.imgur.com/6TrIues.jpg"
+    const val coverApi = "https://coverapi.orell.dev/api/v1/mdaltimage/manga/{uuid}/cover"
```
Comment (arkon) [inline src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt:20]: Wat

Comment (CarlosEsco) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt:20]: he said it was fine to use.  Its what neko and sy are using
