### PR TITLE
SushiScans sources: Update URL & fix search

### LINKED ISSUE #19281: Sushiscan.fr changed for anime-sama.me
### Source information

Sushiscan.fr 1.4.27

### Source language

French

### Source new URL

https://anime-sama.me

### Other details

Sushiscan.fr, which already had the same name as Sushiscan.net, has changed its name to anime-sama.me, taking over from anime-sama.fr.
Quite dishonest on their part, but at least this extension works, unlike the other two mentioned.
Thank you.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #19298: Sushi-scan : search function doesn't work
### Source information

Sushi-scan 1.4.36

### Source language

French

### Steps to reproduce

1. Open the extension
2. Search for a manga
3. Extension shows you "No results found" regardless of it is there or not

### Expected behavior

The extension should show the manga that match the search

### Actual behavior

The extension shows "No results found" regardless of whether or not the actual site shows results if you search there
Screenshot_20231213-103857
Screenshot_20231213-103926

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KirinRaikage**
Checklist:

I don't know whether we should keep the new name of the source, or retain this name. The new name currently conflicts with another source which has exactly the same name, though. SushiScanFr redirects to this new URL now, anyway.

Closes #19281 
Closes #19298 

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/mangathemesia/sushiscan/src/SushiScan.kt [hunk 1]
```diff
@@ -32,6 +35,9 @@ class SushiScan : MangaThemesia("Sushi-Scan", "https://sushiscan.net", "fr", man
         else -> SManga.UNKNOWN
     }
 
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request =
+        GET("$baseUrl/page/$page/?s=$query")
```
Comment (alessandrojean) [inline multisrc/overrides/mangathemesia/sushiscan/src/SushiScan.kt:39]: This is error-prone to URL query parameter encoding issues. You can use OkHttp's HttpUrl builder instead.

```suggestion
    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
        val url = "$baseUrl/page/$page/".toHttpUrl().newBuilder()
            .addQueryParameter("s", query)
            .build()
            
        return GET(url, headers)
    }
```

Make sure to add the proper imports.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: multisrc/overrides/mangathemesia/sushiscan/src/SushiScan.kt (hunk 1 above)
Comment (KirinRaikage) [reply multisrc/overrides/mangathemesia/sushiscan/src/SushiScan.kt]: OK, is this URL query parameter encoding issue stuff new?
