### PR TITLE
Niceoppai: fix duplicate manga

### LINKED ISSUE #17154: Niceoppai: It's show up to the same manga.
### Source information

Niceoppai 1.4.27

### Source language

TH

### Steps to reproduce

**When entering the extention niceoppai will show the same manga as in the picture.**

**And when we enter the manga, it will show the following message.**

### Expected behavior

**It should be able to list manga normally like any other extention.**

**Example**
<a href="https://pic.in.th/image/cNNrh"></a>

### Actual behavior

**It should be able to list manga normally like any other extention.**

**Example**
<a href="https://pic.in.th/image/cNNrh"></a>

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

**In webview it works fine but in tachiyomi it doesn't work properly.  It can't fetch the correct manga list.**

**Webview**
<a href="https://pic.in.th/image/cWMiC"></a>

**Tachiyomi**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
The URL was not found on the page, updated to a more generic selector. Title also contained chapter names, which has also been addressed. `manga.initialized` is false by default, so it was removed.

Closes #17154

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/th/niceoppai/src/eu/kanade/tachiyomi/extension/th/niceoppai/Niceoppai.kt [hunk 1]
```diff
@@ -45,11 +45,10 @@ class Niceoppai : ParsedHttpSource() {
     override fun popularMangaSelector() = "div.nde"
     override fun popularMangaFromElement(element: Element): SManga {
```
Comment (AntsyLich) [inline src/th/niceoppai/src/eu/kanade/tachiyomi/extension/th/niceoppai/Niceoppai.kt:46]:
```kt
override fun popularMangaFromElement(element: Element): SManga = SManga.create().apply {
    title = element.selectFirst("div.det a")!!.text()
    element.select("div.cvr").let {
        setUrlWithoutDomain(it.select("a").attr("href"))
        thumbnail_url = it.select("img").attr("abs:src")
    }
}
```
