### PR TITLE
Dex fixes

### LINKED ISSUE #6846: [Bug] MangaDex: "newChapterListJson["results"] must not be null" error
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: 1.2.106

## Steps to reproduce
1. Attempt to open or migrate "Wonder Cat Kyuu-chan"

### Expected behavior
It loads.

### Actual behavior
Error: `newChapterListJson["results"] must not be null`

### LINKED ISSUE #6847: [Bug] MangaDex: Searches with no results return null
## Device information
- Tachiyomi version: r3346 (cb203ef0)
- Android version: 11

## Source information
- Name: MangaDex
- Extension version: 1.2.106

## Steps to reproduce
1. Search mangadex
2. Observe a null object error

### Expected behavior
1. Indicate no results found

### Actual behavior
`Not a JSON Object: null`

### LINKED ISSUE #6848: [Bug] Mangadex: Can't open chapters
---

## Device information
- Tachiyomi version: r3346 (cb203ef0) 
- Android version: 9

## Source information
- Name: mangadex
- Extension version: 1.2.106

## Steps to reproduce
1. migrate MD title to MD
2. open chapter

### Expected behavior
open to chapter view

### Actual behavior
toast notif java.lang.String cannot be cast to java.lang.Integer

## Other details

Ive tried a bunch of different titles+chapters but still get the same notif
also tried some titles not in my library but in the mangadex source
migrating seemed ok
some chapters that i had downloaded prior to mangadex going down still open as expected

### LINKED ISSUE #6850: [Bug] Tachi Crashes on mangadex settings
## Device information
* Tachiyomi version: 0.10.12
* Android version: 7.0
* Device: Redmi Note 4X
* Mangadex extension : 1.2.106

## Steps to reproduce
1. Goto mangadex extension settings
2. Tap on settings icon for English and tachi crashes

### Expected behavior
English settings for mangadex extension
### Actual behavior
Instead of English setting it crashes

## Other details
Crash log is attached
Screenshot_2021-05-06-07-15-07-059_eu kanade tachiyomi
[Crash Log](https://app.box.com/s/ukdddjnzv3mt3tihgclv961x3ya75o46)

### PR DESCRIPTION
**Pull request by CarlosEsco**
Closes #6848
Closes #6847
Closes #6846
Closes #6850

Fixes missings tags, adds a temp cover, fixes preference for data saver crashing alt languages, made content rating and language tags more clear.

### CODE REVIEW

**Review by arkon — APPROVED** [review]

File: src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt [hunk 1]
```diff
@@ -67,30 +66,29 @@ class MangaDexVietnamese : MangaDex("vi")
 class MangaDexGreek : MangaDex("el")
 class MangaDexBulgarian : MangaDex("bg")
 class MangaDexSpanishSpain : MangaDex("es")
-class MangaDexPortugueseBrazil : MangaDex("pt-BR")
+class MangaDexPortugueseBrazil : MangaDex("pt-br")
```
Comment (alessandrojean) [inline src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: Changing it to `pt-br` instead of `pt-BR` changed the id of the source and made the Mangadex in Portuguese to be separed from the other Brazilian extensions. Can this be reverted? 👀

Comment (CarlosEsco) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: @riztard add to your pr

Comment (arkon) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: The other ones ended up changing the locales too, so we may need to revisit this.

Comment (CarlosEsco) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: > The other ones ended up changing the locales too, so we may need to revisit this.

Add a constant for locales in extensions lib

Comment (arkon) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: Can't you just use the ones defined in the JDK?

Comment (Riztard) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: if the other changes is correct one maybe need to override the id?

Comment (alessandrojean) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: > Can't you just use the ones defined in the JDK?

Some languages (like Brazilian Portuguese) doesn't have their own constants in `Locale`, as far as I know.

https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html

Comment (arkon) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: Fair. If we add constants somewhere, it can't be in the extensions-lib though, since that's a compile-only stubs package.

Comment (CarlosEsco) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: Also at least in this instance, the id is actually used by dex to filter chapters

Comment (arkon) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: Shouldn't we go back to what we had before v5, with both what we use internally and what MD uses?

Comment (CarlosEsco) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt:69]: we can but dex lang codes changed to iso ones.  No more gb == english etc
