### PR TITLE
MangaDex Cover Qulity Setting

### LINKED ISSUE #8262: Mangadex: Covers take a long time to load due to downloading full size
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.1.11 (6/6/21 07:55)

### Android version

10

### Source information

Mangadex 1.2.126

### Steps to reproduce

1. Open Latest (scroll if required)
2. Watch network usage increase by amount equivalent to the full size cover.
3. Watch cover not loading until large full size cover loaded

PS: not reproducible all the time since only some uses stupidly large cover.

### Expected behavior

The smaller thumbnail should be downloaded.

### Actual behavior

It takes a long time to download some full size cover at 7MB+,

causing the rest of the cover not to load until they are done loading.

### Other details

Since the covers isn't store in a convenient location as far as I am aware of, I can't really verify that it downloaded the larger cover and can only guess from the amount of data used, the time it took and the source code.

Also, I notice the thumbnails on the mangadex website when loading from a computer is postfixed with `.512.jpg`

The api says `.256.jpg` is available too.

API:  https://api.mangadex.org/docs.html#section/Retrieving-Covers-from-the-API/Construct-Cover-URLs

Relevant parts of the code:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/08779023fb5216c34d6bfbdc3d41b2df6521c578/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexInterceptors.kt#L93

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/08779023fb5216c34d6bfbdc3d41b2df6521c578/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt#L173-L175

### PR DESCRIPTION
**Pull request by FourTOne5**
Closes #8262

### CODE REVIEW

File: src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt [hunk 1]
```diff
@@ -33,6 +33,24 @@ object MDConstants {
...
     const val prefixChSearch = "ch:"
 
+    const val coverQualityPref = "thumbnailQuality"
+
+    fun getCoverQualityPreferenceKey(dexLang: String): String {
+        return "${coverQualityPref}_$dexLang"
+    }
+    
+    fun getCoverQualityPreferenceEntries(): Array<String> {
+        return arrayOf("Orginal", "512px Wide", "256px Wide")
```
Comment (CarlosEsco) [inline src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt:43]: Just say original, medium, low

**Review by CarlosEsco — CHANGES_REQUESTED** [review]

**Review by CarlosEsco — APPROVED** [review]

**Comment by asl97** [comment]
Didn't seem to apply retroactively to covers that hasn't been downloaded but added to database (covers are only loaded when scroll into view),

I guess there is some kind of cache, clearing everything seem to get it to properly load the smaller images.
