### PR TITLE
re-manga: Fix latest, chapter parsing

### LINKED ISSUE #10061: re-manga: The latest page not working
### Source information

re-manga 1.2.1

### Steps to reproduce

Opening the latest tab

### Expected behavior

The latest page show manga updates in the site

### Actual behavior

The latest page don't show anything

### Tachiyomi version

0.12.3-399

### Android version

10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #10061 

minor refactor, improve caching for popular and latest

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt [hunk 1]
```diff
@@ -108,15 +109,30 @@ class REManga : ParsedHttpSource() {
...
+            }
+
+            element.select(".date").first()?.text()?.let {
+                date_upload = parseDate(it)
+            }
         }
     }
 
+    private fun parseDate(date: String): Long {
+        return SimpleDateFormat("MMM d, yyy", Locale("ar")).parse(date)?.time ?: 0L
```
Comment (alessandrojean) [inline src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt:133]: Better to create the date formatter object as a constant, otherwise it will be recreated every chapter.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt (hunk 1 above)
Comment (vetleledaal) [reply src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt:133]: I'm not too familiar with Kotlin/Android/Tachiyomi development. Which one would be the most preferable in this case? 

```kotlin
private val dateFormat = SimpleDateFormat(/**/)

private val dateFormat by lazy {
    SimpleDateFormat(/**/)
}

companion object {
    private val DATE_FORMATTER = SimpleDateFormat(/**/)
}

companion object {
    private val DATE_FORMATTER by lazy {
        SimpleDateFormat(/**/)
    }
}
```

Comment (alessandrojean) [reply src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt:133]: All are accepted and valid solutions, but the ones that uses `by lazy` are the best because the formatter will only be generated in the first time it's accessed.
