### PR TITLE
YonaBar: update domain

### LINKED ISSUE #10691: YonaBar changed to https://yonabar.net/
### Source information

YonaBar 1.2.15

### Steps to reproduce

Website yonabar change the link to https://yonabar.net/

### Expected behavior

Change link to https://yonabar.net/

### Actual behavior

The link now not working closed

### Tachiyomi version

r4507

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #10691 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -451,7 +451,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Yaoi.mobi", "https://yaoi.mobi", "en", isNsfw = true, className = "YaoiManga", pkgName = "yaoimanga", overrideVersionCode = 4),
         SingleLang("YaoiScan", "https://yaoiscan.com", "en", isNsfw = true),
         SingleLang("YaoiToon", "https://yaoitoon.com", "en", isNsfw = true),
-        SingleLang("YonaBar", "https://yonabar.com", "ar", isNsfw = true),
+        SingleLang("YonaBar", "https://yonabar.net", "ar", isNsfw = true, overrideVersionCode = 2),
```
Comment (alessandrojean) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:454]:
```suggestion
        SingleLang("YonaBar", "https://yonabar.net", "ar", isNsfw = true, overrideVersionCode = 1),
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]

**Comment by vetleledaal** [comment]
oops. force-pushed the change and rebased to master
