### PR TITLE
[Otaku Sanctuary] Move back to main endpoint for fetching chapter pages

### LINKED ISSUE #15058: Otaku Sanctuary Can't read some manga
### Source information and language

OtakuSanctuary 1.3.1 

### Steps to reproduce

1. Open 1 random manga 
2. Open 1 chap random

### Expected behavior

Screenshot_20230122-003740

### Actual behavior

Screenshot_20230122-003740

### Tachiyomi version

0.14.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beerpiss**
Closes #15058

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/otakusanctuary/OtakuSanctuary.kt [hunk 1]
```diff
@@ -181,34 +181,92 @@ open class OtakuSanctuary(
...
+                    if (url.startsWith("/api/Value/")) {
+                        val serverUrl = if (helper.otakusanLang() == "us" && indexServer == 1) {
+                            US_SERVERS[0]
+                        } else {
+                            SERVERS[indexServer]
+                        }
+                        url = "$serverUrl$url"
+                    }
+
+                    if (url.contains("otakusan.net_") && !url.contains("fetcher.otakuscan.net") && !url.contains("fetcher.otakuscan.net")) {
```
Comment (arkon) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/otakusanctuary/OtakuSanctuary.kt:212]: 2nd and 3rd conditions are the same?
