### PR TITLE
HentaiHere: show all tags, minor fixes

### LINKED ISSUE #10789: Tags support for Hentaihere
### Describe your suggested feature

Currently, there's no content tags support on the extension, but it's available on the website.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #10789

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/hentaihere/src/eu/kanade/tachiyomi/extension/en/hentaihere/HentaiHere.kt [hunk 1]
```diff
@@ -138,24 +148,32 @@ class HentaiHere : ParsedHttpSource() {
...
-                .trim()
-            genre = genres.joinToString(", ") { it.text() }
-            status = if (licensed != null) {
-                SManga.LICENSED
-            } else {
-                document.select("#info > div:nth-child(4) > a").text().trim().toStatus()
-            }
-            thumbnail_url = document.select("#cover img").attr("src")
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
+        val categories = document.select("#info .text-info:contains(Cat) ~ a")
```
Comment (vetleledaal) [inline src/en/hentaihere/src/eu/kanade/tachiyomi/extension/en/hentaihere/HentaiHere.kt:152]: This is intentional, as it's mistyped on the site
