### PR TITLE
Remove dead sites and fix other

### LINKED ISSUE #18214: EGY Manga
### Source name

EGY Manga

### Source language

العربية

### Source link

http://ww25.egymanga.net/?subid1=20230929-0644-275a-a678-a01d5889706a

### Other details

ww25.egymanga.net/0.0.0.0:80

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18335: Mangamanhua source is down
### Source name

MangaManhua

### Source language

English

### Source link

https://mangamanhua.online

### Other details

Starting 10/01/2023, Mangamanhua extension was returning 404 error. Upon going to the source website, the following error returned.
image
It might be permanent or they changed domain, it's hard to tell.

Thank you!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18377: Türkçe Manga: Source is down
### Source name

Türkçe Manga 1.4.33

### Source language

Turkish 

### Source link

https://turkcemanga.com/

### Other details

This site has been shut down.

IMG_20231005_121352

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18379: Geasstoon
### Source name

Geasstoon

### Source language

Turkish 

### Source link

http://ww7.geasstoon.com/

### Other details

This source has been shut down. 
IMG_20231005_122631
IMG_20231005_122643

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18381: Atikrost
### Source name

Atikrost

### Source language

Turkish 

### Source link

https://atikrost.com/

### Other details

Source is down and website is closed.
IMG_20231005_132544
IMG_20231005_132554

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18382: Gecenin Lordu
### Source name

Gecenin Lordu 

### Source language

Turkish 

### Source link

http://ww38.geceninlordu.com/

### Other details

Source is down and website is closed. 
IMG_20231005_132949
IMG_20231005_133002

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18800: AkuManga: it's now eng not ar and +18
### Source information

AkuManga 1.4.32

### Source language

Arabic 

### Steps to reproduce

Apparently they switched to eng and +18

### Expected behavior

Money talking 
Screenshot_2023-10-29-23-37-48-292_eu kanade tachiyomi-edit

### Actual behavior

~

### Tachiyomi version

14.

### Android version

13

### Other details

Flip 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #18801: Fug manga: can be removed
### Source name

Fug manga 1.4.32

### Source language

Arabic 

### Source link

https://fugmanga.net/

### Other details

Dead 
Screenshot_2023-10-29-23-44-04-859_eu kanade tachiyomi-edit

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Qlend**
Fix date format for king of shojo
Make MangaStic to NSFW
Closes #18800 
Closes #18801
Closes #18214
Closes #18381
Closes #18379
Closes #18377
Closes #18335
Closes #18382

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -28,7 +28,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Adult Webtoon", "https://adultwebtoon.com", "en", isNsfw = true, overrideVersionCode = 1),
         SingleLang("Akimangá", "https://akimanga.com", "pt-BR", isNsfw = true, className = "Akimanga"),
         SingleLang("Akuma no Tenshi", "https://akumanotenshi.com", "pt-BR", className = "AkumaNoTenshi"),
-        SingleLang("AkuManga", "https://akumanga.com", "ar", overrideVersionCode = 1),
+        SingleLang("AkuManga", "https://akumanga.com", "en", isNsfw = true),
```
Comment (vetleledaal) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt:31]:
```suggestion
        SingleLang("AkuManga", "https://akumanga.com", "en", isNsfw = true, overrideVersionCode = 2),
```

**Review by vetleledaal — CHANGES_REQUESTED** [review]
