### PR TITLE
ComickFun: Updated API and fixed error when API returns no url for a page

### LINKED ISSUE #14786: Comickfun API page with no url
### Source information and language

Comickfun 1.3.18 (English)

### Steps to reproduce

1. Open "I Log in Alone" manhua
2. Open chapter 161

### Expected behavior

Chapter is supposed to load

### Actual behavior

The app reports an error, "Field url is required for the type with serial name 'eu.kanade.tachiyomi.extension.all.comickfun.Page' but it was missing at path $.chapter.images[3] "

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

This occurs because of the [API from comickfun](https://api.comick.app/chapter/qqy1k?tachiyomi=true) not including an url for the 3rd entry. The comickfun team said, "The image was broken even on the translator site." Is it possible to have a default option where if the url or the entry is null it skips that entry or something?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by buhbbl**
Fixes and Closes #14786.
Addresses #14788 by changing the API URL.

The slug and hid changes in #14788 have not been addressed in this PR.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by buhbbl** [comment]
Implemented the use of the new search API endpoint which should address the issue #14668.

Further updated to now address the deprecated API calls. 

But will need to be re-visited once ext-lib 1.4 is released as currently the app will store the slugs in the url property instead of the hid which will cause issues if the slugs are changed.

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 1]
```diff
@@ -297,4 +302,26 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
...
+                    addPathSegment("mapping")
+                    addQueryParameter("slugs", mangaSlug)
+                }.toString(),
+                headers
+            )
+        ).execute()
+
+        /** If the API does not contain the ID for the slug, return the slug back **/
+        return try {
+            JSONObject(response.body?.string() ?: "").getString(mangaSlug)
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:322]: Use kotlinx.serialization instead, replace the usages of `org.json` with the `json` instance you already have available in the class.

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 1 above)
Comment (buhbbl) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:322]: Need to use parseToJsonElement instead of using Dto as the API does not have a defined structure. 

Will update it.

Comment (alessandrojean) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt]: No problem in using the kotlinx.serialization's JsonElement if it's the case 👍🏻

**Review by alessandrojean — APPROVED** [review]

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt [hunk 2]
```diff
@@ -297,4 +302,22 @@ abstract class ComickFun(override val lang: String, private val comickFunLang: S
     override fun getFilterList() = FilterList(
         getFilters()
     )
+
+    /** Map the slug to comic ID as slug might be changes by comic ID will not. **/
+    // TODO: Cleanup once ext-lib 1.4 is released.
+    private fun slugMapRequest(mangaSlug: String): String {
```
Comment (alessandrojean) [inline src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:308]: Better to rename the method as it's not returning a request, it's rather fetching data.

```kotlin
private fun findCurrentSlug(oldSlug: String): String {
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt (hunk 2 above)
Comment (buhbbl) [reply src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt:308]: got it
