### PR TITLE
Madara: fix lateinit not initialized for some source

### LINKED ISSUE #14210: Ext Leviathan 1.3.38 error
### Source information and language

Leviathan 1.3.38

### Steps to reproduce

Global update/refresh chapters for all leviathan entries

### Expected behavior

Refresh chapters/update with no issues

### Actual behavior

Receiving error during global update:

"! lateinit property title has not been initialized
  # Leviatan Scans (EN)
    - The Black mage Who Reincarnated after 66666 Years
    - The Mage Who Absorbs Abilities
    - The reincarnated swordsman with 9999 strength wants to become a magician!"
Screenshot_20221109_193810_Chrome

AND

Receiving error during chapter refresh:

lateinit property title has not been initialized
Screenshot_20221109_183828_Tachiyomi

### Tachiyomi version

0.14.2 (2022-10-31 17:42)

### Android version

Android 13 Samsung S22 Ultra

### Other details

Screenshot_20221109_191622_Settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14214: lateinit property title has not been initialized
### Source information and language

Manhwa-raw Multi 

### Steps to reproduce

First step: I click the "Manhwa-raw" Multi language extension

Second step: I click the title that I want to read and refresh it to get new chapter update.

Issue: it says "lateinit property title has not been initialized" when refreshed

### Expected behavior

This should be happening: Refresh the Title and new chapter appears

### Actual behavior

This happened instead: it says lateinit property title has not been initialized and no new chapter was updated

### Tachiyomi version

0.14.2

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Riztard**
- check if initialized for tag/genre filtering

closes #14210
closes #14214

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt [hunk 1]
```diff
@@ -665,14 +665,16 @@ abstract class Madara(
                 .toMutableSet()
 
             // add tag(s) to genre
+            val mangaTitle = if (manga.initialized) manga.title else "not initialized"
```
Comment (stevenyomi) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt:668]: You are doing it the wrong way. `manga.initialized` is a custom field and is always `false` because you just created it.

```suggestion
            val mangaTitle = try {
                manga.title
            } catch (_: UninitializedPropertyAccessException) {
                "not initialized"
            }
```
