### PR TITLE
<dmzj>: fix url

### LINKED ISSUE #5501: [Bug] dmzj : failed to load
## Device information
- Tachiyomi version: 0.10.7
- Android version: 11

## Source information
- Name: dmzj
- Extension version: 1.2.12

## Steps to reproduce
1. check dmzj source for the latest content

### Expected behavior
normal display content

### Actual behavior
unable to resolve host "v2.api.dmzj.com"：No address associated with hostname

## Other details
this source changed the domain name from dmzj.com to dmzj1.com

### PR DESCRIPTION
**Pull request by OncePunchedMan**
Closes #5501 

i fixed the urls for getting all info, but it seems like they didn't change the chapter urls on their site:

_should be images.dmzj1._

you can't read on the website either. so we have to wait until they change it. extension is ready tho

### CODE REVIEW

**Comment by erinacio** [comment]
Got `Unable to resolve host "v3api.dmzj11.com": No address associated with hostname`, is this expected?

File: src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt [hunk 1]
```diff
@@ -186,6 +186,7 @@ class Dmzj : HttpSource() {
             // example url: http://v3api.dmzj.com/chapter/44253/101852.json
             val url = response.request().url().toString()
                 .replace("api.m", "v3api")
+                .replace("dmzj", "dmzj1")
```
Comment (erinacio) [inline src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt:189]: If original site has already switched to `dmzj1.com` domain, this would rewrite it to `dmzj11.com`.

**Comment by OncePunchedMan** [comment]
@erinacio 
loading fine for me now since they changed their images.dmzj to imgages.dmzj1.
try this guide https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis

**Comment by erinacio** [comment]
> @erinacio
> loading fine for me now since they changed their images.dmzj to imgages.dmzj1.
> try this guide https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis

Nope. I still got `v3api.dmzj11.com` error, with comic 47974 and chapter 103952.

**Comment by erinacio** [comment]
Seems that it happens only when `https://api.m.dmzj1.com/comic/chapter/$cid/$chapter_id.html` failed. The url got from `response.request().url()` may already use `dmzj1.com`, no need for `.replace("dmzj", "dmzj1")`.

**Comment by Oldwangtouchtouchdoge** [comment]
> 
> 
> Seems that it happens only when `https://api.m.dmzj1.com/comic/chapter/$cid/$chapter_id.html` failed. The url got from `response.request().url()` may already use `dmzj1.com`, no need for `.replace("dmzj", "dmzj1")`.

I found same problem, `api.m.dmzj1.com` failed seems only happen when the comic is hidden or show as ban in dmzj website, some of them can still parse correctly by `v3api.dmzj1.com`.
