### PR TITLE
FMReader Fixes Pt.2: The Encryption Strikes Back

### LINKED ISSUE #7054: [Bug] ManhuaScan: Error Bad Decrypt
## Device information
- Tachiyomi version: Stable 0.10.12
- Android version: 11

## Source information
- Name: ManhuaScan
- Extension version: 1.2.6 

## Steps to reproduce
1. Click on Resume
2. Open/Resume Chapter

### Expected behavior
It should open and/or resume the manga/manhua.

### Actual behavior
Forced closed. Showing Error. Open SSL
Internal_Bad Decrypt.

## Other details
[Screenshot_20210516-230304_Tachiyomi](https://user-images.githubusercontent.com/84158024/118440234-3416e080-b69c-11eb-90f6-71860ead0e7c.jpg)

### LINKED ISSUE #7055: [Bug] Heroscan: Error Bad Decrypt
## Device information
- Tachiyomi version: v0.10.12
- Android version: 11

## Source information
- Name: HeroScan
- Extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Page to load and appear.

### Actual behavior
Page force closed, with a tag stated, error: 1e000065: Cipher functions: OPENS SL_internal:BAD_DECRYPT 

## Other details
Screenshot_20210517-141155_Tachiyomi

### PR DESCRIPTION
**Pull request by h-hyuuga**
alternate title: Play Cat and Mouse with HeroScan, ManhuaScan, and ManhwaHot

This pull request restores functionality to the aforementioned extensions and applies a harsh rate limiting limit.

Aside: There's no chance this fix survives the day. Once it breaks again, we'll probably have to declare them `won't fix`.

Closes #7055
Closes #7054

### CODE REVIEW

File: multisrc/overrides/fmreader/heroscan/src/HeroScan.kt [hunk 1]
```diff
@@ -1,11 +1,13 @@
 package eu.kanade.tachiyomi.extension.en.heroscan
 
+import eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor
 import eu.kanade.tachiyomi.multisrc.fmreader.FMReader
 import eu.kanade.tachiyomi.source.model.SChapter
 import okhttp3.OkHttpClient
 
 class HeroScan : FMReader("HeroScan", "https://heroscan.com", "en") {
     override val client: OkHttpClient = super.client.newBuilder()
+            .addInterceptor(RateLimitInterceptor(1, period=1))
```
Comment (Riztard) [inline multisrc/overrides/fmreader/heroscan/src/HeroScan.kt:10]: `(1, period=1)` just make it `(1)` if i remember right default period is 1

File: multisrc/overrides/fmreader/heroscan/additional.gradle.kts [hunk 2]
```diff
@@ -0,0 +1,4 @@
+
+dependencies {
+    implementation project(':lib-ratelimit')
+}
```
Comment (Riztard) [inline multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: maybe just put it to default folder, so only need one

**Comment by Riztard** [comment]
update the version?

File: multisrc/overrides/fmreader/heroscan/src/HeroScan.kt (hunk 1 above)
Comment (h-hyuuga) [reply multisrc/overrides/fmreader/heroscan/src/HeroScan.kt]: done

**Comment by h-hyuuga** [comment]
> update the version?

i really forgot to do everything haha

File: multisrc/overrides/fmreader/heroscan/additional.gradle.kts (hunk 2 above)
Comment (h-hyuuga) [reply multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: I'm not super clear on the build process on Android.

Would there be an issues with injecting that dependency for every fmreader extension?

Comment (Riztard) [reply multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: i dont think so, there is no issue for wpmangasream i think

Comment (kedestin) [reply multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: good to know, but  I'll probably leave it as is since this extension probably won't survive the day.

Comment (h-hyuuga) [reply multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: good to know, 

will probably leave as is since the relevant extensions probably won't last the day

Comment (Riztard) [reply multisrc/overrides/fmreader/heroscan/additional.gradle.kts:4]: lol
