### PR TITLE
naver: fix author parsing and handle on hiatus status

### LINKED ISSUE #17948: Naver Comic extension broken
### Source information

Naver Comic 1.4.3

### Source language

Korean

### Steps to reproduce

1. Open naver comic
2. Go to any manhwa
3. Manhwa doesn't load, throws exception

Possibly due to website redesign

### Expected behavior

Manhwa loads / updates

### Actual behavior

Manhwa doesn't load
Error_Screenshot

### Tachiyomi version

TachiyomiSY Preview r530

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #17966: Naver Webtoon Extension Broken
### Source information

Naver Comic 1.4.3

### Source language

Korea

### Steps to reproduce

1. Open naver comic
2. Go to any manhwa
3. Manhwa doesn't load, throws exception

Possibly due to website redesign

### Expected behavior

Manhwa loads / updates

### Actual behavior

Manhwa doesn't load
Screenshot_2023-09-16-09-59-45-713_eu kanade tachiyomi

### Tachiyomi version

Tachiyomi 0.14.6

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by metonyms**
Closes #17966
Closes #17948

naver's API changed how author info was stored in the response

additionally they added a secondary `rest` flag for series that are on hiatus. previously those series would have the `finished` flag set to true instead

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/ko/navercomic/src/eu/kanade/tachiyomi/extension/ko/navercomic/NaverComicBase.kt [hunk 1]
```diff
@@ -108,16 +108,21 @@ abstract class NaverComicBase(protected val mType: String) : ParsedHttpSource()
...
+            publishingStatus = SManga.ON_HIATUS
+        }
 
         return SManga.create().apply {
             title = manga.titleName
             author = authors
             description = manga.synopsis
             thumbnail_url = manga.thumbnailUrl
-            status = if (manga.finished) SManga.COMPLETED else SManga.ONGOING
+            status = publishingStatus
```
Comment (alessandrojean) [inline src/ko/navercomic/src/eu/kanade/tachiyomi/extension/ko/navercomic/NaverComicBase.kt:125]:
```suggestion
            status = when {
                manga.finished -> SManga.COMPLETED
                manga.rest -> SManga.ON_HIATUS
                else -> SManga.ONGOING
            }
```

**Review by alessandrojean — CHANGES_REQUESTED** [review]

File: src/ko/navercomic/src/eu/kanade/tachiyomi/extension/ko/navercomic/NaverComicBase.kt (hunk 1 above)
Comment (metonyms) [reply src/ko/navercomic/src/eu/kanade/tachiyomi/extension/ko/navercomic/NaverComicBase.kt]: thanks for the suggestion. this is my first time writing any kotlin so i didn't realize you could use that expression that way
