### PR TITLE
[Komga] change language to `all`, add more logs

### LINKED ISSUE #9335: [Bug] Komga extension wrong region label
### Source information

Komga 1.2.31

### Steps to reproduce

1. install komga extension from "all" type extensions

### Expected behavior

1. komga should show up in "all" type extensions

### Actual behavior

1. The extension shows up as "English" in installed extensions
2. The sources don't show up if "English" extensions are turned off

### Tachiyomi version

0.12.2

### Android version

android 10

### Other details

The extension shows up in "all" (すべて for me) when first selecting and installing it, but after install it's labeled as "English". I've asked the komga dev why it isn't in "all", he answered thusly:
"It is all, probably tachiyomi does a default, but ask on their discord".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by gotson**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Annotated `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- [x] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

- This changes the language from `en` to `all`. Closes #9335
- Response bodies are properly closed by using `.use { }`.
- added more logs when loading filters, in order to troubleshoot #9347 and #6047

### CODE REVIEW

File: src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt [hunk 1]
```diff
@@ -350,10 +369,17 @@ open class Komga(suffix: String = "") : ConfigurableSource, HttpSource() {
...
     override val supportsLatest = true
     private val LOG_TAG = "extension.all.komga${if (suffix.isNotBlank()) ".$suffix" else ""}"
 
+    // keep the previous ID when lang was "en", so that preferences and manga bindings are not lost
+    override val id by lazy {
+        val key = "${name.toLowerCase()}/en/$versionId"
+        val bytes = MessageDigest.getInstance("MD5").digest(key.toByteArray())
+        (0..7).map { bytes[it].toLong() and 0xff shl 8 * (7 - it) }.reduce(Long::or) and Long.MAX_VALUE
+    }
+
```
Comment (curche) [inline src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt:382]: The hardcoded values could be used directly, since we know them from previous ext versions and also [here](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/99bf5049c66fb576996c84bfd6ebbf77b432ebe6/index.json#L2502) 

almost psuedo-code
```kotlin
override val id = when (name) {
  "Komga"     -> 4508733312114627536
  "Komga (2)" -> 8074481155021144106
  "Komga (3)" -> 5132811728275817394
}
```

Comment (gotson) [reply src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt:382]: what would be the benefit of doing this?

Comment (curche) [reply src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt:382]: basically, my intention was to just avoid having to do the ID computation in the extension. 
Not sure how much it gains over lazily computing it (probably not much)

Comment (curche) [reply src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt:382]: Actually, I almost PRd a fix myself in https://github.com/curche/tachiyomi-extensions/commit/9373b60e51cbd68fc78da3e1dcacd81f2abb23c5 :smile: 
where I did it in the `KomgaFactory` instead (was trying it out while checking the other PR #9361)

modifying `Komga` class as below
 ```kotlin
 open class Komga(suffix: String, override val id: Long) : ConfigurableSource, HttpSource()
 ```
and then creating individual sources like so
```kotlin
listOf(
            Komga("",4508733312114627536),
            Komga("2",8074481155021144106),
            Komga("3",5132811728275817394)
)
```

Comment (CarlosEsco) [reply src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt:382]: gonna merge and this can be revisted in your PR curche
