### PR TITLE
Webnovel updates

### LINKED ISSUE #15305: Original Quality Image From WebNovel Comics
### Source name and language

WebNovel (English)

### Describe your suggested feature

The image quality is different when downloaded from hakuneko and tachiyomi.
- So please add an option to download the original image from WebNovel comics.
- See below attached images for reference. The original image is not blurry and is higher quality.

### Other details

For Example, [The Ultimate Scheming System, Chapter 001](https://www.webnovel.com/comic/the-ultimate-scheming-system_12272676305179201),
- The first image is 800 x 1122.
- The same image downloaded from hakuneko is 1536 x 2155.

- ### Image Downloaded Using Tachiyomi/Image that can be seen on webnovel comics while reading

- ### Image Downloaded Using Hakuenko

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15849: Webnovel.com strange behaviour when "Privileged Chapters" are unlocked
### Source information and language

Webnovel.com 1.4.6

### Steps to reproduce

1. Unlock a "Priviledged"/Early Access Chapter on the Webnovel app.
2. Log in through WebView in Tachiyomi.
3. Refresh list.

### Expected behavior

Shows list of all chapters available through their website.

### Actual behavior

List only shows the Privileged Chapters.

### Tachiyomi version

TachiyomiSY r504

### Android version

Android 10

### Other details

Privileged Chapters aren't actually available through their website, only the app, so they can't even be opened through Tachi.

Webnovel also _very_ frequently logs me out, but I'm not sure that's something that can be resolved on Tachi's end, so I didn't wanna open a separate issue. Just thought I'd mention it in case it can be solved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AntsyLich**
Closes #15305
Closes #15849
Also use features from ext-lib 1.4

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/webnovel/src/eu/kanade/tachiyomi/extension/en/webnovel/Webnovel.kt [hunk 1]
```diff
@@ -351,7 +330,7 @@ class Webnovel : HttpSource() {
         private const val QUERY_SEARCH_PATH = "/search/result"
         private const val FILTER_SEARCH_PATH = "/category/categoryAjax"
 
-        private const val MIGRATE_MESSAGE = "Migrate this entry from \"Webnovel.com\" to \"Webnovel.com\" to update url"
+        private const val MIGRATE_MESSAGE = "Migrate this entry from \"Webnovel.com\" to \"Webnovel.com\" to update it's url"
```
Comment (arkon) [inline src/en/webnovel/src/eu/kanade/tachiyomi/extension/en/webnovel/Webnovel.kt:333]:
```suggestion
        private const val MIGRATE_MESSAGE = "Migrate this entry from \"Webnovel.com\" to \"Webnovel.com\" to update its URL"
```
