### PR TITLE
Replace Manga1000/1001 with Comick and MangaPro

### LINKED ISSUE #11047: Remove manga1000/manga1001
### Source information

MangaRaw1.2.4

### Steps to reproduce

open manga1000/manga1001

### Expected behavior

load manga list

### Actual behavior

manga1000 404
manga1001 time out

### Tachiyomi version

0.13.1

### Android version

Android 11 MIUI12.5

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ringosham**
Checklist:

Closes #11047 

Both Manga1000 and Manga1001 has been [DMCA'd and shut down by Shogakukan, Shueisha, Kadokawa and Kodansha](https://torrentfreak.com/major-manga-publishers-try-to-identify-operators-of-massive-pirate-sites-211211/). And judging from the news sources, Manga1002 might also soon be taken down. Plus it has a completely different layout from the old one. Not sure if it's even the same site, so I'm not going to spend time on that one.

comick.top and mangapro.top are the copycats (Not the same owner) of these two sites. They look the same visually but have slightly different html layout. It's also filled with clickjacking ads. **Highly not recommend viewing the site in WebView**

Users are required to migrate their library to the new sources.

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Yea I meant make a factory where you can have these as added and share the code.  Not use the dead sites and just point them to the copycats

**Comment by ringosham** [comment]
Oh in that case should I reopen the PR to remove the extension?

**Comment by ringosham** [comment]
Ok then in that case I'll reopen the PR to remove the extension.

I'm not sure if Manga1002 is the same site so I'm just going to remove it.

File: src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt [hunk 1]
```diff
@@ -7,29 +7,32 @@ import eu.kanade.tachiyomi.source.model.SChapter
...
-
     override fun headersBuilder(): Headers.Builder {
         return super.headersBuilder().add("Referer", baseUrl)
     }
 
-    override fun popularMangaRequest(page: Int) = GET("$baseUrl/seachlist/page/$page/?cat=-1", headers)
+    // comick.top doesn't have a popular manga page
+    // redirect to latest manga request
+    override fun popularMangaRequest(page: Int): Request {
+        return if (name == "Comick")
```
Comment (Riztard) [inline src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt:31]: use override instead of adding some specific thing to factory

File: src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt [hunk 2]
```diff
@@ -58,8 +62,18 @@ abstract class MangaRaw(
     override fun searchMangaNextPageSelector() = popularMangaNextPageSelector()
 
     override fun mangaDetailsParse(document: Document) = SManga.create().apply {
-        genre = document.select("p.has-text-color:has(strong) a").joinToString { it.text() }
-        description = document.select("p.has-text-color:not(:has(strong))").first().text()
+        // All manga details are located in the same <p> tag
+        // So here are some jank way of extracting them
+        // comick.top doesn't have author or genre info
+        if (name != "Comick") {
```
Comment (Riztard) [inline src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt:68]: this too, use override

File: src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt [hunk 3]
```diff
@@ -7,29 +7,32 @@ import eu.kanade.tachiyomi.source.model.SChapter
...
-import okhttp3.Protocol
+import okhttp3.Request
 import org.jsoup.nodes.Document
 import org.jsoup.nodes.Element
 
 abstract class MangaRaw(
     override val name: String,
-    override val baseUrl: String
+    override val baseUrl: String,
+    private val imageSelector: String = ".wp-block-image > img"
```
Comment (Riztard) [inline src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt:17]: this one too maybe just use override
