### PR TITLE
[ConstellarScans] Descramble images, decode page URLs, add rate limit

### LINKED ISSUE #14955: Constellar scans blocking?
### Source information and language

Constellar scans

### Steps to reproduce

Open manhwa "unlock her heart" latest chapter 

### Expected behavior

Should open chapters

### Actual behavior

Not opening correct chapter 

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

Screenshot_Tachiyomi
Not working with mobile user agent
Screenshot_Tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beerpiss**
Closes #14955 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: multisrc/overrides/mangathemesia/constellarscans/src/ConstellarScans.kt [hunk 1]
```diff
@@ -1,7 +1,161 @@
...
+        }.joinToString("")
+        val fragment = fragmentAndImageCount.substring(0..31)
+        val imageCount = fragmentAndImageCount.substring(32).toInt()
+
+        val pages = mutableListOf<Page>()
+        for (i in 1..imageCount) {
+            pages.add(
+                Page(
+                    i,
+                    imageUrl = "$encodedUploadsPath/$fragment/${i.toString().padStart(5, '0')}.webp?$DESCRAMBLE=yes"
```
Comment (stevenyomi) [inline multisrc/overrides/mangathemesia/constellarscans/src/ConstellarScans.kt:90]:
```suggestion
                    imageUrl = "$encodedUploadsPath/$fragment/${i.toString().padStart(5, '0')}.webp#$DESCRAMBLE"
```

Use fragment so this tag doesn't get sent to the server. Use `url.fragment` in interceptor to check this part.

Another good alternative:

```kotlin
class DescrambleTag

override fun imageRequest(page: Page) =
    GET(page.imageUrl!!, headers).newBuilder()
        .tag(DescrambleTag::class.java, DescrambleTag())
        .build()

// in interceptor
if (request.tag(DescrambleTag::class.java) == null) return response
```

**Comment by mobi2002** [comment]
The scanlator was complaining in their discord that tachi sends too many requests, so maybe add some rate limit as well.
